; --- Motorola 6809 backend (Vectrex) title='Demo' origin=$0000 ---
        ORG $0000
; Basic Vectrex header (placeholder)
    FCB $67,$20,$56,$45,$43,$54,$52,$45,$58,$20,$47,$41,$4D,$45,$20
    FCB $00,$00,$00,$00

JSR INIT_ENGINE
JSR MAIN
END_LOOP: BRA END_LOOP

ADD: ; function
; --- function add ---
add:
    LDD VAR_ARG0
    STD VAR_A
    LDD VAR_ARG1
    STD VAR_B
    LDD VAR_A
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_B
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    RTS

NEG: ; function
; --- function neg ---
neg:
    LDD VAR_ARG0
    STD VAR_A
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_A
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    RTS

ACCUMULATE: ; function
; --- function accumulate ---
accumulate:
    LDD VAR_ARG0
    STD VAR_A
    LDD VAR_ARG1
    STD VAR_B
    LDD VAR_ARG2
    STD VAR_C
    LDD VAR_ARG3
    STD VAR_D
    LDD VAR_A
    STD RESULT
    LDU #VAR_TOTAL
    STU TMPPTR
    STX ,U
    LDD VAR_TOTAL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_B
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDU #VAR_TOTAL
    STU TMPPTR
    STX ,U
    LDD VAR_TOTAL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_C
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDU #VAR_TOTAL
    STU TMPPTR
    STX ,U
    LDD VAR_TOTAL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_D
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDU #VAR_TOTAL
    STU TMPPTR
    STX ,U
    LDD VAR_TOTAL
    STD RESULT
    RTS

MAIN: ; function
; --- function main ---
main:
    LDD #3
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #5
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    JSR ADD
    LDU #VAR_S
    STU TMPPTR
    STX ,U
    LDD #7
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    JSR NEG
    LDU #VAR_N
    STU TMPPTR
    STX ,U
    LDD #1
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #3
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #4
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR ACCUMULATE
    LDU #VAR_T
    STU TMPPTR
    STX ,U
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_I
FOR_0: ; for loop
    LDD VAR_I
    LDD #10
    STD RESULT
    LDX RESULT
    CPD RESULT
    BHS FOR_END_1
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_I
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR LINE
    LDD #2
    STD RESULT
    LDX RESULT
    LDD VAR_I
    ADDD ,X
    STD VAR_I
    BRA FOR_0
FOR_END_1: ; for end
    LDD VAR_S
    STD RESULT
    LDD RESULT
    BEQ AND_FALSE_4
    LDD VAR_N
    STD RESULT
    LDD RESULT
    BEQ NOT_TRUE
    LDD #0
    STD RESULT
    BRA NOT_END
NOT_TRUE:
    LDD #1
    STD RESULT
NOT_END:
    LDD RESULT
    BEQ AND_FALSE_4
    LDD #1
    STD RESULT
    BRA AND_END_5
AND_FALSE_4:
    LDD #0
    STD RESULT
AND_END_5:
    LDD RESULT
    BEQ IF_NEXT_3
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR LINE
    BRA IF_END_2
IF_END_2:
    LDD VAR_S
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_T
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_N
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    RTS

; Runtime helpers
MUL16:
    LDD MUL_A
    STD MUL_RES
    LDD #0
    STD MUL_TMP
    LDD MUL_B
    STD MUL_CNT
MUL16_LOOP:
    LDD MUL_CNT
    BEQ MUL16_DONE
    LDD MUL_CNT
    ANDA #1
    BEQ MUL16_SKIP
    LDD MUL_RES
    ADDD MUL_TMP
    STD MUL_TMP
MUL16_SKIP:
    LDD MUL_RES
    ASLB
    ROLA
    STD MUL_RES
    LDD MUL_CNT
    LSRA
    RORB
    STD MUL_CNT
    BRA MUL16_LOOP
MUL16_DONE:
    LDD MUL_TMP
    STD RESULT
    RTS

DIV16:
    LDD #0
    STD DIV_Q
    LDD DIV_A
    STD DIV_R
    LDD DIV_B
    BEQ DIV16_DONE
DIV16_LOOP:
    LDD DIV_R
    SUBD DIV_B
    BLO DIV16_DONE
    STD DIV_R
    LDD DIV_Q
    ADDD #1
    STD DIV_Q
    BRA DIV16_LOOP
DIV16_DONE:
    LDD DIV_Q
    STD RESULT
    RTS

; Variables
VAR_A: FDB 0
VAR_B: FDB 0
VAR_C: FDB 0
VAR_D: FDB 0
VAR_I: FDB 0
VAR_N: FDB 0
VAR_S: FDB 0
VAR_T: FDB 0
VAR_TOTAL: FDB 0
; Call argument scratch space
VAR_ARG0: FDB 0
VAR_ARG1: FDB 0
VAR_ARG2: FDB 0
VAR_ARG3: FDB 0
