; --- Motorola 6809 backend (Vectrex) title='UNTITLED' origin=$0000 ---
        ORG $0000
; Basic Vectrex header (placeholder)
    FCB $67,$20,$56,$45,$43,$54,$52,$45,$58,$20,$47,$41,$4D,$45,$20
    FCB $00,$00,$00,$00

JSR INIT_ENGINE
JSR MAIN
END_LOOP: BRA END_LOOP

ADD: ; function
; --- function add ---
add:
    LDD VAR_ARG0
    STD VAR_A
    LDD VAR_ARG1
    STD VAR_B
    LDD VAR_A
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_B
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    RTS

MAIN: ; function
; --- function main ---
main:
    LDD #16
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #10
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    JSR ADD
    LDU #VAR_S
    STU TMPPTR
    STX ,U
    LDD VAR_S
    STD RESULT
    LDD RESULT
    COMA
    COMB
    STD RESULT
    LDU #VAR_INV
    STU TMPPTR
    STX ,U
    LDD VAR_S
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
SHL_LOOP: LDA TMPRIGHT+1
    BEQ SHL_DONE
    ASLB
    ROLA
    DEC TMPRIGHT+1
    BRA SHL_LOOP
SHL_DONE: STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
SHR_LOOP: LDA TMPRIGHT+1
    BEQ SHR_DONE
    LSRA
    RORB
    DEC TMPRIGHT+1
    BRA SHR_LOOP
SHR_DONE: STD RESULT
    LDU #VAR_SH
    STU TMPPTR
    STX ,U
    LDD VAR_SH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #16
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; quotient in RESULT, need remainder: A - Q*B
    LDD DIV_A
    STD TMPLEFT
    LDD RESULT
    STD MUL_A
    LDD DIV_B
    STD MUL_B
    JSR MUL16
    ; product in RESULT, subtract from original A (TMPLEFT)
    LDD TMPLEFT
    SUBD RESULT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_INV
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #255
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ANDA TMPRIGHT+1
    ANDB TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    EORA TMPRIGHT+1
    EORB TMPRIGHT
    STD RESULT
    LDU #VAR_R
    STU TMPPTR
    STX ,U
    LDD #0
    STD RESULT
    LDU #VAR_ACC
    STU TMPPTR
    STX ,U
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_I
FOR_0: ; for loop
    LDD VAR_I
    LDD #16
    STD RESULT
    LDX RESULT
    CPD RESULT
    BHS FOR_END_1
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_I
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ANDA TMPRIGHT+1
    ANDB TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDU #VAR_ACC
    STU TMPPTR
    STX ,U
    LDD #2
    STD RESULT
    LDX RESULT
    LDD VAR_I
    ADDD ,X
    STD VAR_I
    BRA FOR_0
FOR_END_1: ; for end
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_R
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDU #VAR_ACC
    STU TMPPTR
    STX ,U
    LDD VAR_ACC
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_S
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_R
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    RTS

; Runtime helpers
MUL16:
    LDD MUL_A
    STD MUL_RES
    LDD #0
    STD MUL_TMP
    LDD MUL_B
    STD MUL_CNT
MUL16_LOOP:
    LDD MUL_CNT
    BEQ MUL16_DONE
    LDD MUL_CNT
    ANDA #1
    BEQ MUL16_SKIP
    LDD MUL_RES
    ADDD MUL_TMP
    STD MUL_TMP
MUL16_SKIP:
    LDD MUL_RES
    ASLB
    ROLA
    STD MUL_RES
    LDD MUL_CNT
    LSRA
    RORB
    STD MUL_CNT
    BRA MUL16_LOOP
MUL16_DONE:
    LDD MUL_TMP
    STD RESULT
    RTS

DIV16:
    LDD #0
    STD DIV_Q
    LDD DIV_A
    STD DIV_R
    LDD DIV_B
    BEQ DIV16_DONE
DIV16_LOOP:
    LDD DIV_R
    SUBD DIV_B
    BLO DIV16_DONE
    STD DIV_R
    LDD DIV_Q
    ADDD #1
    STD DIV_Q
    BRA DIV16_LOOP
DIV16_DONE:
    LDD DIV_Q
    STD RESULT
    RTS

; Variables
VAR_A: FDB 0
VAR_ACC: FDB 0
VAR_B: FDB 0
VAR_I: FDB 0
VAR_INV: FDB 0
VAR_R: FDB 0
VAR_S: FDB 0
VAR_SH: FDB 0
; Call argument scratch space
VAR_ARG0: FDB 0
VAR_ARG1: FDB 0
VAR_ARG2: FDB 0
VAR_ARG3: FDB 0
