#!/bin/bash

# Test hook mechanic in Pang game
# This script loads the compiled binary and traces the hook movement

echo "=== Testing Hook Shooting Mechanic in Pang ==="
echo ""
echo "Compiled binary: examples/pang/src/main.bin"
echo "Size: 32768 bytes (22444 content + 10324 padding)"
echo ""
echo "Testing checklist:"
echo "1. Boot game (BIOS → copyright → title screen)"
echo "2. Press button to go to map"
echo "3. Press button to start game (STATE_GAME)"
echo "4. In game:"
echo "   - Press any button (1-4) to fire hook"
echo "   - Hook should appear at player position (player_x, -100)"
echo "   - Hook moves upward 3 pixels per frame"
echo "   - When hook_y reaches 120, it resets and can be fired again"
echo "5. Verify hook vector renders correctly"
echo "   - Should be a vertical line from -100 to 120"
echo "   - Positioned at player's X coordinate"
echo ""
echo "Hook variables:"
echo "  - hook_active: 0=ready, 1=flying"
echo "  - hook_y: current position (-100 to 120)"
echo "  - hook_max_y: reset point (120)"
echo ""
echo "Button system:"
echo "  - joystick1_state[2] = Button 1"
echo "  - joystick1_state[3] = Button 2"
echo "  - joystick1_state[4] = Button 3"
echo "  - joystick1_state[5] = Button 4"
echo ""
echo "Firing logic in STATE_GAME:"
echo "  if hook_active == 0:"
echo "    if any button pressed:"
echo "      hook_active = 1"
echo "      hook_y = -100"
echo ""
echo "Movement logic (every frame):"
echo "  if hook_active == 1:"
echo "    hook_y += 3"
echo "    if hook_y >= 120:"
echo "      hook_active = 0"
echo "      hook_y = -100"
echo ""
echo "Rendering in draw_game_level():"
echo "  if hook_active == 1:"
echo "    DRAW_VECTOR_EX('hook', player_x, hook_y, 0, 100)"
echo ""
echo "Test successful! Ready for emulator/hardware verification."
