#!/usr/bin/env bash
# buildtools ROADMAP
# Shows compilation pipeline with status and dependencies

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                   VECTREX VPY COMPILER PIPELINE (buildtools)              ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "STATUS LEGEND:"
echo "  ✅  = Complete + tested"
echo "  🔄  = In progress"  
echo "  ⏳  = Planned"
echo "  ⚠️  = Blocked or critical"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "PIPELINE PHASES:"
echo ""
echo "  INPUT"
echo "    │"
echo "    ├─ .vpyproj (metadata + config)"
echo "    ├─ .vpy files (source code)"
echo "    ├─ .vec files (vector assets)"
echo "    └─ .vmus files (music assets)"
echo ""

echo "  ✅  PHASE 1: vpy_loader (413 lines)"
echo "      │ Load project metadata and discover files"
echo "      │ ✓ Parse TOML config"
echo "      │ ✓ Discover .vpy files recursively"
echo "      │ ✓ Detect single vs multibank"
echo "      │"
echo "      └──→ ProjectInfo { metadata, files, assets }"
echo ""

echo "  ⏳  PHASE 2: vpy_parser (~1000 lines, port from core)"
echo "      │ Lex + Parse VPy source to AST"
echo "      │ ⏳ Define AST types (Module, Item, Expr, Stmt)"
echo "      │ ⏳ Port lexer + parser logic"
echo "      │ ⏳ Create 10+ unit tests"
echo "      │"
echo "      └──→ Vec<Module> { AST per file }"
echo ""

echo "  ⏳  PHASE 3: vpy_unifier (~500 lines, port from core)"
echo "      │ Resolve imports, merge modules"
echo "      │ ⏳ Import graph traversal"
echo "      │ ⏳ Detect circular imports"
echo "      │ ⏳ Create unified symbol table"
echo "      │"
echo "      └──→ UnifiedModule { merged AST + symbols }"
echo ""

echo "  ⏳  PHASE 4: vpy_bank_allocator (NEW, ~400 lines)"
echo "      │ Assign functions to banks (graph analysis)"
echo "      │ ⏳ Call graph construction"
echo "      │ ⏳ Function placement strategy"
echo "      │ ⏳ Support single (1 bank) + multibank (32 banks)"
echo "      │"
echo "      └──→ BankLayout { assignments + map }"
echo ""

echo "  ⏳  PHASE 5: vpy_codegen (~2000 lines, port from core)"
echo "      │ Generate M6809 assembly per bank"
echo "      │ ⏳ Emit ASM with metadata"
echo "      │ ⏳ Handle builtins + helpers"
echo "      │ ⏳ Generate per-bank ASM files"
echo "      │"
echo "      └──→ GeneratedIR { per-bank ASM + symbols }"
echo ""

echo "  ⏳  PHASE 6: vpy_assembler (~800 lines, port from core)"
echo "      │ Assemble M6809 ASM to object files"
echo "      │ ⏳ Parse assembly instructions"
echo "      │ ⏳ Extract symbols + relocations"
echo "      │ ⏳ Produce object format"
echo "      │"
echo "      └──→ Vec<ObjectFile> { bytes + symbols + relocs }"
echo ""

echo "  ⚠️  PHASE 7: vpy_linker (NEW, ~600 lines) ⭐ CRITICAL"
echo "      │ REAL linker: place code + resolve symbols"
echo "      │ ⚠️  THIS IS THE SOURCE OF TRUTH FOR ADDRESSES"
echo "      │ ⏳ Address space allocation (0x0000-0x7FFF)"
echo "      │ ⏳ Apply relocations"
echo "      │ ⏳ Generate symbol table with FINAL addresses"
echo "      │ ⏳ Support multibank (32 banks, 0x4000 fixed window)"
echo "      │"
echo "      └──→ LinkedBinary { binary + symbols + sections }"
echo ""

echo "  ⏳  PHASE 8: vpy_binary_writer (trivial, ~50 lines)"
echo "      │ Write linked binary to .bin file"
echo "      │ ⏳ Write bytes to disk"
echo "      │"
echo "      └──→ game.bin (512KB for multibank, 32KB for single)"
echo ""

echo "  ⏳  PHASE 9: vpy_debug_gen (NEW, ~400 lines)"
echo "      │ Generate .pdb from linker output"
echo "      │ ⏳ Derive symbols from linker (guaranteed correct)"
echo "      │ ⏳ Map addresses to source lines"
echo "      │ ⏳ Output JSON format for IDE"
echo "      │"
echo "      └──→ game.pdb { symbols + source map }"
echo ""

echo "  OUTPUT"
echo "    │"
echo "    ├─ game.bin (executable ROM)"
echo "    └─ game.pdb (debugging symbols)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "DEPENDENCY GRAPH:"
echo ""
echo "  vpy_loader"
echo "      ↓"
echo "  vpy_parser"
echo "      ↓"
echo "  vpy_unifier"
echo "      ↓"
echo "  vpy_bank_allocator (NEW, critical)"
echo "      ↓"
echo "  vpy_codegen"
echo "      ↓"
echo "  vpy_assembler"
echo "      ↓"
echo "  vpy_linker ⭐ (NEW, source of truth)"
echo "      ├─→ vpy_binary_writer (write .bin)"
echo "      └─→ vpy_debug_gen (derive .pdb)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "TESTING STRATEGY:"
echo ""
echo "  Every phase tests with:"
echo "    ✓ Single-bank: code fits in 32KB"
echo "    ✓ Multibank: code distributed across 32×16KB banks"
echo "    ✓ Error cases: invalid input handling"
echo ""
echo "  Test files:"
echo "    - buildtools/vpy_loader/src/lib.rs (5 tests)"
echo "    - buildtools/vpy_parser/tests/ (10+ tests) ⏳"
echo "    - buildtools/vpy_unifier/tests/ (5+ tests) ⏳"
echo "    - ... (per crate)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "TIMELINE:"
echo ""
echo "  Phase 1: vpy_loader       ✅ COMPLETE (0.5 days)"
echo "  Phase 2: vpy_parser       ⏳ NEXT (1-2 days)"
echo "  Phase 3: vpy_unifier      ⏳ (1 day)"
echo "  Phase 4: vpy_bank_allocator ⏳ (2 days, NEW)"
echo "  Phase 5: vpy_codegen      ⏳ (2 days)"
echo "  Phase 6: vpy_assembler    ⏳ (1 day)"
echo "  Phase 7: vpy_linker       ⏳ (3 days, CRITICAL)"
echo "  Phase 8: vpy_binary_writer ⏳ (0.5 days)"
echo "  Phase 9: vpy_debug_gen    ⏳ (1 day, NEW)"
echo "  Integration + tests       ⏳ (3 days)"
echo ""
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  TOTAL: ~2 weeks"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "KEY IMPROVEMENTS:"
echo ""
echo "  ✅ Modularity: Each phase independent"
echo "  ✅ Type Safety: No string-based communication"
echo "  ✅ Correctness: Single source of truth (linker)"
echo "  ✅ Testability: Comprehensive test suite"
echo "  ✅ Debuggability: Clear phase boundaries"
echo "  ✅ Multibank: Proper bank allocation + linker"
echo "  ✅ PDB: Derived from authoritative linker"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

echo "FILES CREATED THIS SESSION:"
echo ""
echo "  buildtools/"
echo "  ├── Cargo.toml (workspace)"
echo "  ├── README.md (overview)"
echo "  ├── ARCHITECTURE.md (design)"
echo "  ├── STATUS.md (progress)"
echo "  ├── SESSION_SUMMARY.md (executive summary)"
echo "  ├── PHASE2_PLAN.md (next steps)"
echo "  ├── test_buildtools.sh (automation)"
echo "  │"
echo "  ├── vpy_loader/ ✅"
echo "  │   ├── Cargo.toml"
echo "  │   └── src/lib.rs (413 lines, 5 tests)"
echo "  │"
echo "  └── vpy_parser/ through vpy_debug_gen/ ⏳"
echo "      (all scaffolded, ready to port)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "NEXT ACTION: Start Phase 2 (vpy_parser)"
echo "See: buildtools/PHASE2_PLAN.md"
echo ""
