; --- Motorola 6809 backend (Vectrex) title='BOUNCING TRAIL' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8,$50,$20,-$45
    FCC "BOUNCING TRAIL"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

MAIN_LOOP:
    JSR Wait_Recal
    LDA #$D0
    TFR A,DP
    JSR Intensity_5F
    JSR Reset0Ref
    JSR MAIN
    BRA MAIN_LOOP

I_BRIGHT EQU 127
I_MEDIUM EQU 80
I_DIM EQU 48
I_FAINT EQU 24
SCREEN_LEFT EQU 65446
SCREEN_RIGHT EQU 90
SCREEN_TOP EQU 70
SCREEN_BOTTOM EQU 65466
BALL_SIZE EQU 6
TRAIL_LENGTH EQU 8
UPDATE_TRAIL: ; function
; --- function update_trail ---
    RTS

UPDATE_BALL_PHYSICS: ; function
; --- function update_ball_physics ---
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_X
    STU TMPPTR
    STX ,U
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_Y
    STU TMPPTR
    STX ,U
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65452
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLE CT_2
    BRA CE_3
CT_2:
    LDD #1
    STD RESULT
CE_3:
    LDD RESULT
    LBEQ IF_NEXT_1
    LDD #65452
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_X
    STU TMPPTR
    STX ,U
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_VEL_X
    STU TMPPTR
    STX ,U
    LBRA IF_END_0
IF_NEXT_1:
IF_END_0:
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #64
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGE CT_6
    BRA CE_7
CT_6:
    LDD #1
    STD RESULT
CE_7:
    LDD RESULT
    LBEQ IF_NEXT_5
    LDD #64
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_Y
    STU TMPPTR
    STX ,U
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_VEL_Y
    STU TMPPTR
    STX ,U
    LBRA IF_END_4
IF_NEXT_5:
IF_END_4:
    RTS

DRAW_TRAIL: ; function
; --- function draw_trail ---
    LDD VAR_TRAIL_X7
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_12
    BRA CE_13
CT_12:
    LDD #1
    STD RESULT
CE_13:
    LDD RESULT
    BNE OR_TRUE_10
    LDD VAR_TRAIL_Y7
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_14
    BRA CE_15
CT_14:
    LDD #1
    STD RESULT
CE_15:
    LDD RESULT
    BNE OR_TRUE_10
    LDD #0
    STD RESULT
    BRA OR_END_11
OR_TRUE_10:
    LDD #1
    STD RESULT
OR_END_11:
    LDD RESULT
    LBEQ IF_NEXT_9
    LDD VAR_TRAIL_X7
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y7
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #2
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #24
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_8
IF_NEXT_9:
IF_END_8:
    LDD VAR_TRAIL_X6
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_20
    BRA CE_21
CT_20:
    LDD #1
    STD RESULT
CE_21:
    LDD RESULT
    BNE OR_TRUE_18
    LDD VAR_TRAIL_Y6
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_22
    BRA CE_23
CT_22:
    LDD #1
    STD RESULT
CE_23:
    LDD RESULT
    BNE OR_TRUE_18
    LDD #0
    STD RESULT
    BRA OR_END_19
OR_TRUE_18:
    LDD #1
    STD RESULT
OR_END_19:
    LDD RESULT
    LBEQ IF_NEXT_17
    LDD VAR_TRAIL_X6
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y6
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #2
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #24
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_16
IF_NEXT_17:
IF_END_16:
    LDD VAR_TRAIL_X5
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_28
    BRA CE_29
CT_28:
    LDD #1
    STD RESULT
CE_29:
    LDD RESULT
    BNE OR_TRUE_26
    LDD VAR_TRAIL_Y5
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_30
    BRA CE_31
CT_30:
    LDD #1
    STD RESULT
CE_31:
    LDD RESULT
    BNE OR_TRUE_26
    LDD #0
    STD RESULT
    BRA OR_END_27
OR_TRUE_26:
    LDD #1
    STD RESULT
OR_END_27:
    LDD RESULT
    LBEQ IF_NEXT_25
    LDD VAR_TRAIL_X5
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y5
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #3
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #24
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_24
IF_NEXT_25:
IF_END_24:
    LDD VAR_TRAIL_X4
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_36
    BRA CE_37
CT_36:
    LDD #1
    STD RESULT
CE_37:
    LDD RESULT
    BNE OR_TRUE_34
    LDD VAR_TRAIL_Y4
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_38
    BRA CE_39
CT_38:
    LDD #1
    STD RESULT
CE_39:
    LDD RESULT
    BNE OR_TRUE_34
    LDD #0
    STD RESULT
    BRA OR_END_35
OR_TRUE_34:
    LDD #1
    STD RESULT
OR_END_35:
    LDD RESULT
    LBEQ IF_NEXT_33
    LDD VAR_TRAIL_X4
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y4
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #3
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #48
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_32
IF_NEXT_33:
IF_END_32:
    LDD VAR_TRAIL_X3
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_44
    BRA CE_45
CT_44:
    LDD #1
    STD RESULT
CE_45:
    LDD RESULT
    BNE OR_TRUE_42
    LDD VAR_TRAIL_Y3
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_46
    BRA CE_47
CT_46:
    LDD #1
    STD RESULT
CE_47:
    LDD RESULT
    BNE OR_TRUE_42
    LDD #0
    STD RESULT
    BRA OR_END_43
OR_TRUE_42:
    LDD #1
    STD RESULT
OR_END_43:
    LDD RESULT
    LBEQ IF_NEXT_41
    LDD VAR_TRAIL_X3
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y3
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #4
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #48
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_40
IF_NEXT_41:
IF_END_40:
    LDD VAR_TRAIL_X2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_52
    BRA CE_53
CT_52:
    LDD #1
    STD RESULT
CE_53:
    LDD RESULT
    BNE OR_TRUE_50
    LDD VAR_TRAIL_Y2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_54
    BRA CE_55
CT_54:
    LDD #1
    STD RESULT
CE_55:
    LDD RESULT
    BNE OR_TRUE_50
    LDD #0
    STD RESULT
    BRA OR_END_51
OR_TRUE_50:
    LDD #1
    STD RESULT
OR_END_51:
    LDD RESULT
    LBEQ IF_NEXT_49
    LDD VAR_TRAIL_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #4
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #80
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_48
IF_NEXT_49:
IF_END_48:
    LDD VAR_TRAIL_X1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_60
    BRA CE_61
CT_60:
    LDD #1
    STD RESULT
CE_61:
    LDD RESULT
    BNE OR_TRUE_58
    LDD VAR_TRAIL_Y1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BNE CT_62
    BRA CE_63
CT_62:
    LDD #1
    STD RESULT
CE_63:
    LDD RESULT
    BNE OR_TRUE_58
    LDD #0
    STD RESULT
    BRA OR_END_59
OR_TRUE_58:
    LDD #1
    STD RESULT
OR_END_59:
    LDD RESULT
    LBEQ IF_NEXT_57
    LDD VAR_TRAIL_X1
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRAIL_Y1
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #5
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #80
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_56
IF_NEXT_57:
IF_END_56:
    RTS

DRAW_CURRENT_BALL: ; function
; --- function draw_current_ball ---
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD #6
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD #127
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    JSR DRAW_CIRCLE
    CLRA
    CLRB
    STD RESULT
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #127
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR VECTREX_DRAW_LINE
    CLRA
    CLRB
    STD RESULT
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #127
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR VECTREX_DRAW_LINE
    CLRA
    CLRB
    STD RESULT
    RTS

DRAW_SCENE_ELEMENTS: ; function
; --- function draw_scene_elements ---
    LDD #65466
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #60
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_4
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    LDA #$46
    LDB #$A6
    JSR Moveto_d ; move to (166, 70)
    LDA #$30
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B4
    JSR Draw_Line_d ; dy=0, dx=-65356
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    LDA #$BA
    LDB #$A6
    JSR Moveto_d ; move to (166, 186)
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B4
    JSR Draw_Line_d ; dy=0, dx=-65356
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    LDA #$46
    LDB #$A6
    JSR Moveto_d ; move to (166, 70)
    CLR Vec_Misc_Count
    LDA #$74
    LDB #$00
    JSR Draw_Line_d ; dy=65396, dx=0
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    LDA #$46
    LDB #$5A
    JSR Moveto_d ; move to (90, 70)
    CLR Vec_Misc_Count
    LDA #$74
    LDB #$00
    JSR Draw_Line_d ; dy=65396, dx=0
    CLRA
    CLRB
    STD RESULT
    LDD VAR_FRAME_COUNT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #31
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ANDA TMPRIGHT+1
    ANDB TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #16
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLT CT_66
    BRA CE_67
CT_66:
    LDD #1
    STD RESULT
CE_67:
    LDD RESULT
    LBEQ IF_NEXT_65
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGT CT_70
    BRA CE_71
CT_70:
    LDD #1
    STD RESULT
CE_71:
    LDD RESULT
    BEQ AND_FALSE_72
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGT CT_74
    BRA CE_75
CT_74:
    LDD #1
    STD RESULT
CE_75:
    LDD RESULT
    BEQ AND_FALSE_72
    LDD #1
    STD RESULT
    BRA AND_END_73
AND_FALSE_72:
    LDD #0
    STD RESULT
AND_END_73:
    LDD RESULT
    LBEQ IF_NEXT_69
    LDD #40
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_0
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_68
IF_NEXT_69:
IF_END_68:
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLT CT_78
    BRA CE_79
CT_78:
    LDD #1
    STD RESULT
CE_79:
    LDD RESULT
    BEQ AND_FALSE_80
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGT CT_82
    BRA CE_83
CT_82:
    LDD #1
    STD RESULT
CE_83:
    LDD RESULT
    BEQ AND_FALSE_80
    LDD #1
    STD RESULT
    BRA AND_END_81
AND_FALSE_80:
    LDD #0
    STD RESULT
AND_END_81:
    LDD RESULT
    LBEQ IF_NEXT_77
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_1
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_76
IF_NEXT_77:
IF_END_76:
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLT CT_86
    BRA CE_87
CT_86:
    LDD #1
    STD RESULT
CE_87:
    LDD RESULT
    BEQ AND_FALSE_88
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLT CT_90
    BRA CE_91
CT_90:
    LDD #1
    STD RESULT
CE_91:
    LDD RESULT
    BEQ AND_FALSE_88
    LDD #1
    STD RESULT
    BRA AND_END_89
AND_FALSE_88:
    LDD #0
    STD RESULT
AND_END_89:
    LDD RESULT
    LBEQ IF_NEXT_85
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_3
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_84
IF_NEXT_85:
IF_END_84:
    LDD VAR_VEL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGT CT_94
    BRA CE_95
CT_94:
    LDD #1
    STD RESULT
CE_95:
    LDD RESULT
    BEQ AND_FALSE_96
    LDD VAR_VEL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BLT CT_98
    BRA CE_99
CT_98:
    LDD #1
    STD RESULT
CE_99:
    LDD RESULT
    BEQ AND_FALSE_96
    LDD #1
    STD RESULT
    BRA AND_END_97
AND_FALSE_96:
    LDD #0
    STD RESULT
AND_END_97:
    LDD RESULT
    LBEQ IF_NEXT_93
    LDD #40
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_2
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LBRA IF_END_92
IF_NEXT_93:
IF_END_92:
    LBRA IF_END_64
IF_NEXT_65:
IF_END_64:
    RTS

MAIN: ; function
; --- function main ---
    LDD VAR_FRAME_COUNT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_FRAME_COUNT
    STU TMPPTR
    STX ,U
    LDD VAR_FRAME_COUNT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ANDA TMPRIGHT+1
    ANDB TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BEQ CT_102
    BRA CE_103
CT_102:
    LDD #1
    STD RESULT
CE_103:
    LDD RESULT
    LBEQ IF_NEXT_101
    JSR UPDATE_TRAIL
    LBRA IF_END_100
IF_NEXT_101:
IF_END_100:
    JSR UPDATE_BALL_PHYSICS
    LDD #80
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    JSR VECTREX_FRAME_BEGIN
    CLRA
    CLRB
    STD RESULT
    JSR DRAW_SCENE_ELEMENTS
    JSR DRAW_TRAIL
    JSR DRAW_CURRENT_BALL
    LDD #0
    STD RESULT
    RTS

    INCLUDE "runtime/vectorlist_runtime.asm"
VECTREX_PRINT_TEXT:
    ; Wait_Recal set DP=$D0 and zeroed beam; just load U,Y,X and call BIOS
    LDU VAR_ARG2   ; string pointer (high-bit terminated)
    LDA VAR_ARG1+1 ; Y
    LDB VAR_ARG0+1 ; X
    JSR Print_Str_d
    RTS
; Draw single dynamic line. Args: (x0,y0,x1,y1,intensity) low bytes.
; Uses BIOS Draw_Line_d directly (A=dy, B=dx).
; Preconditions: DP is $D0 after Wait_Recal.
VECTREX_DRAW_LINE:
    ; Intensity
    LDA VAR_ARG4+1
    JSR Intensity_a
    ; Move to start (y in A, x in B)
    LDA VAR_ARG1+1
    LDB VAR_ARG0+1
    JSR Moveto_d
    ; Compute deltas (end-start)
    LDA VAR_ARG2+1
    SUBA VAR_ARG0+1
    STA VLINE_DX
    LDA VAR_ARG3+1
    SUBA VAR_ARG1+1
    STA VLINE_DY
    ; Clamp dx to +/-63
    LDA VLINE_DX
    CMPA #63
    BLE DLX_OK_HI
    LDA #63
DLX_OK_HI: CMPA #-64
    BGE DLX_OK_LO
    LDA #-64
DLX_OK_LO: STA VLINE_DX
    ; Clamp dy to +/-63
    LDA VLINE_DY
    CMPA #63
    BLE DLY_OK_HI
    LDA #63
DLY_OK_HI: CMPA #-64
    BGE DLY_OK_LO
    LDA #-64
DLY_OK_LO: STA VLINE_DY
    ; Draw line (Vec_Misc_Count left to BIOS)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS
VECTREX_FRAME_BEGIN:
    LDA VAR_ARG0+1
    JSR Intensity_a
    JSR Reset0Ref
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
TMPLEFT   EQU RESULT+2
TMPRIGHT  EQU RESULT+4
TMPPTR    EQU RESULT+6
VAR_BALL_X EQU RESULT+26
VAR_BALL_Y EQU RESULT+28
VAR_FRAME_COUNT EQU RESULT+30
VAR_TRAIL_X0 EQU RESULT+32
VAR_TRAIL_X1 EQU RESULT+34
VAR_TRAIL_X2 EQU RESULT+36
VAR_TRAIL_X3 EQU RESULT+38
VAR_TRAIL_X4 EQU RESULT+40
VAR_TRAIL_X5 EQU RESULT+42
VAR_TRAIL_X6 EQU RESULT+44
VAR_TRAIL_X7 EQU RESULT+46
VAR_TRAIL_Y0 EQU RESULT+48
VAR_TRAIL_Y1 EQU RESULT+50
VAR_TRAIL_Y2 EQU RESULT+52
VAR_TRAIL_Y3 EQU RESULT+54
VAR_TRAIL_Y4 EQU RESULT+56
VAR_TRAIL_Y5 EQU RESULT+58
VAR_TRAIL_Y6 EQU RESULT+60
VAR_TRAIL_Y7 EQU RESULT+62
VAR_VEL_X EQU RESULT+64
VAR_VEL_Y EQU RESULT+66
; String literals (classic FCC + $80 terminator)
STR_0:
    FCC "NE"
    FCB $80
STR_1:
    FCC "NW"
    FCB $80
STR_2:
    FCC "SE"
    FCB $80
STR_3:
    FCC "SW"
    FCB $80
STR_4:
    FCC "TRAIL DEMO"
    FCB $80
; Call argument scratch space
VAR_ARG0 EQU RESULT+68
VAR_ARG1 EQU RESULT+70
VAR_ARG2 EQU RESULT+72
VAR_ARG3 EQU RESULT+74
VAR_ARG4 EQU RESULT+76
VLINE_DX EQU RESULT+78
VLINE_DY EQU RESULT+79
VLINE_STEPS EQU RESULT+80
VLINE_LIST EQU RESULT+81
