; --- Motorola 6809 backend (Vectrex) title='BREAKOUT' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8
    FCB $50
    FCB $20
    FCB $BB
    FCC "BREAKOUT"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

    ; *** DEBUG *** main() function code inline (initialization)
    LDD #0
    STD VAR_BALL_X
    LDD #65436
    STD VAR_BALL_Y
    LDD #3
    STD VAR_BALL_VX
    LDD #3
    STD VAR_BALL_VY
    LDD #0
    STD VAR_SCORE
    LDD #1
    STD VAR_BRICK1
    LDD #1
    STD VAR_BRICK2
    LDD #1
    STD VAR_BRICK3
    LDD #1
    STD VAR_BRICK4
    LDD #1
    STD VAR_BRICK5
    LDD #1
    STD VAR_BRICK6
    LDD #1
    STD VAR_BRICK7
    LDD #1
    STD VAR_BRICK8
    LDD #1
    STD VAR_BRICK9
    LDD #1
    STD VAR_BRICK10
    LDD #1
    STD VAR_BRICK11
    LDD #1
    STD VAR_BRICK12
    LDD #1
    STD VAR_BRICK13
    LDD #1
    STD VAR_BRICK14
    LDD #1
    STD VAR_BRICK15
    LDD #1
    STD VAR_BRICK16
    LDD #1
    STD VAR_BRICK17
    LDD #1
    STD VAR_BRICK18
    LDD #0
    STD VAR_FLASH_TIMER
    LDD #80
    STD VAR_INTENSITY
    ; VPy_LINE:40
    LDD #0
    STD RESULT

MAIN:
    JSR Wait_Recal
    LDA #$80
    STA VIA_t1_cnt_lo
    ; *** Call loop() as subroutine (executed every frame)
    JSR LOOP_BODY
    BRA MAIN

LOOP_BODY:
    ; DEBUG: Processing 36 statements in loop() body
    ; DEBUG: Statement 0 - Discriminant(0)
    ; VPy_LINE:44
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BALL_VX
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_X
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 1 - Discriminant(0)
    ; VPy_LINE:45
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BALL_VY
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_Y
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 2 - Discriminant(7)
    ; VPy_LINE:48
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #120
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_2
    LDD #0
    STD RESULT
    BRA CE_3
CT_2:
    LDD #1
    STD RESULT
CE_3:
    LDD RESULT
    LBEQ IF_NEXT_1
    ; VPy_LINE:49
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VX
    STU TMPPTR
    STX ,U
    ; VPy_LINE:50
    LDD #5
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_0
IF_NEXT_1:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65416
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_4
    LDD #0
    STD RESULT
    BRA CE_5
CT_4:
    LDD #1
    STD RESULT
CE_5:
    LDD RESULT
    LBEQ IF_END_0
    ; VPy_LINE:52
    LDD #3
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VX
    STU TMPPTR
    STX ,U
    ; VPy_LINE:53
    LDD #5
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_0
IF_END_0:
    ; DEBUG: Statement 3 - Discriminant(7)
    ; VPy_LINE:56
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #120
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_8
    LDD #0
    STD RESULT
    BRA CE_9
CT_8:
    LDD #1
    STD RESULT
CE_9:
    LDD RESULT
    LBEQ IF_NEXT_7
    ; VPy_LINE:57
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:58
    LDD #5
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_6
IF_NEXT_7:
IF_END_6:
    ; DEBUG: Statement 4 - Discriminant(7)
    ; VPy_LINE:61
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65416
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_12
    LDD #0
    STD RESULT
    BRA CE_13
CT_12:
    LDD #1
    STD RESULT
CE_13:
    LDD RESULT
    LBEQ IF_NEXT_11
    ; VPy_LINE:62
    LDD #3
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:63
    LDD #5
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_10
IF_NEXT_11:
IF_END_10:
    ; DEBUG: Statement 5 - Discriminant(7)
    ; VPy_LINE:67
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #115
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_16
    LDD #0
    STD RESULT
    BRA CE_17
CT_16:
    LDD #1
    STD RESULT
CE_17:
    LDD RESULT
    BEQ AND_FALSE_18
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #125
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_20
    LDD #0
    STD RESULT
    BRA CE_21
CT_20:
    LDD #1
    STD RESULT
CE_21:
    LDD RESULT
    BEQ AND_FALSE_18
    LDD #1
    STD RESULT
    BRA AND_END_19
AND_FALSE_18:
    LDD #0
    STD RESULT
AND_END_19:
    LDD RESULT
    LBEQ IF_NEXT_15
    ; VPy_LINE:68
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65416
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_24
    LDD #0
    STD RESULT
    BRA CE_25
CT_24:
    LDD #1
    STD RESULT
CE_25:
    LDD RESULT
    BEQ AND_FALSE_26
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_28
    LDD #0
    STD RESULT
    BRA CE_29
CT_28:
    LDD #1
    STD RESULT
CE_29:
    LDD RESULT
    BEQ AND_FALSE_26
    LDD #1
    STD RESULT
    BRA AND_END_27
AND_FALSE_26:
    LDD #0
    STD RESULT
AND_END_27:
    LDD RESULT
    BEQ AND_FALSE_30
    LDD VAR_BRICK1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_32
    LDD #0
    STD RESULT
    BRA CE_33
CT_32:
    LDD #1
    STD RESULT
CE_33:
    LDD RESULT
    BEQ AND_FALSE_30
    LDD #1
    STD RESULT
    BRA AND_END_31
AND_FALSE_30:
    LDD #0
    STD RESULT
AND_END_31:
    LDD RESULT
    LBEQ IF_NEXT_23
    ; VPy_LINE:69
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK1
    STU TMPPTR
    STX ,U
    ; VPy_LINE:70
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:71
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:72
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_NEXT_23:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_35
    LDD #0
    STD RESULT
    BRA CE_36
CT_35:
    LDD #1
    STD RESULT
CE_36:
    LDD RESULT
    BEQ AND_FALSE_37
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_39
    LDD #0
    STD RESULT
    BRA CE_40
CT_39:
    LDD #1
    STD RESULT
CE_40:
    LDD RESULT
    BEQ AND_FALSE_37
    LDD #1
    STD RESULT
    BRA AND_END_38
AND_FALSE_37:
    LDD #0
    STD RESULT
AND_END_38:
    LDD RESULT
    BEQ AND_FALSE_41
    LDD VAR_BRICK2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_43
    LDD #0
    STD RESULT
    BRA CE_44
CT_43:
    LDD #1
    STD RESULT
CE_44:
    LDD RESULT
    BEQ AND_FALSE_41
    LDD #1
    STD RESULT
    BRA AND_END_42
AND_FALSE_41:
    LDD #0
    STD RESULT
AND_END_42:
    LDD RESULT
    LBEQ IF_NEXT_34
    ; VPy_LINE:74
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK2
    STU TMPPTR
    STX ,U
    ; VPy_LINE:75
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:76
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:77
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_NEXT_34:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_46
    LDD #0
    STD RESULT
    BRA CE_47
CT_46:
    LDD #1
    STD RESULT
CE_47:
    LDD RESULT
    BEQ AND_FALSE_48
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_50
    LDD #0
    STD RESULT
    BRA CE_51
CT_50:
    LDD #1
    STD RESULT
CE_51:
    LDD RESULT
    BEQ AND_FALSE_48
    LDD #1
    STD RESULT
    BRA AND_END_49
AND_FALSE_48:
    LDD #0
    STD RESULT
AND_END_49:
    LDD RESULT
    BEQ AND_FALSE_52
    LDD VAR_BRICK3
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_54
    LDD #0
    STD RESULT
    BRA CE_55
CT_54:
    LDD #1
    STD RESULT
CE_55:
    LDD RESULT
    BEQ AND_FALSE_52
    LDD #1
    STD RESULT
    BRA AND_END_53
AND_FALSE_52:
    LDD #0
    STD RESULT
AND_END_53:
    LDD RESULT
    LBEQ IF_NEXT_45
    ; VPy_LINE:79
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK3
    STU TMPPTR
    STX ,U
    ; VPy_LINE:80
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:81
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:82
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_NEXT_45:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_57
    LDD #0
    STD RESULT
    BRA CE_58
CT_57:
    LDD #1
    STD RESULT
CE_58:
    LDD RESULT
    BEQ AND_FALSE_59
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_61
    LDD #0
    STD RESULT
    BRA CE_62
CT_61:
    LDD #1
    STD RESULT
CE_62:
    LDD RESULT
    BEQ AND_FALSE_59
    LDD #1
    STD RESULT
    BRA AND_END_60
AND_FALSE_59:
    LDD #0
    STD RESULT
AND_END_60:
    LDD RESULT
    BEQ AND_FALSE_63
    LDD VAR_BRICK4
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_65
    LDD #0
    STD RESULT
    BRA CE_66
CT_65:
    LDD #1
    STD RESULT
CE_66:
    LDD RESULT
    BEQ AND_FALSE_63
    LDD #1
    STD RESULT
    BRA AND_END_64
AND_FALSE_63:
    LDD #0
    STD RESULT
AND_END_64:
    LDD RESULT
    LBEQ IF_NEXT_56
    ; VPy_LINE:84
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK4
    STU TMPPTR
    STX ,U
    ; VPy_LINE:85
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:86
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:87
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_NEXT_56:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_68
    LDD #0
    STD RESULT
    BRA CE_69
CT_68:
    LDD #1
    STD RESULT
CE_69:
    LDD RESULT
    BEQ AND_FALSE_70
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_72
    LDD #0
    STD RESULT
    BRA CE_73
CT_72:
    LDD #1
    STD RESULT
CE_73:
    LDD RESULT
    BEQ AND_FALSE_70
    LDD #1
    STD RESULT
    BRA AND_END_71
AND_FALSE_70:
    LDD #0
    STD RESULT
AND_END_71:
    LDD RESULT
    BEQ AND_FALSE_74
    LDD VAR_BRICK5
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_76
    LDD #0
    STD RESULT
    BRA CE_77
CT_76:
    LDD #1
    STD RESULT
CE_77:
    LDD RESULT
    BEQ AND_FALSE_74
    LDD #1
    STD RESULT
    BRA AND_END_75
AND_FALSE_74:
    LDD #0
    STD RESULT
AND_END_75:
    LDD RESULT
    LBEQ IF_NEXT_67
    ; VPy_LINE:89
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK5
    STU TMPPTR
    STX ,U
    ; VPy_LINE:90
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:91
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:92
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_NEXT_67:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_78
    LDD #0
    STD RESULT
    BRA CE_79
CT_78:
    LDD #1
    STD RESULT
CE_79:
    LDD RESULT
    BEQ AND_FALSE_80
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #120
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_82
    LDD #0
    STD RESULT
    BRA CE_83
CT_82:
    LDD #1
    STD RESULT
CE_83:
    LDD RESULT
    BEQ AND_FALSE_80
    LDD #1
    STD RESULT
    BRA AND_END_81
AND_FALSE_80:
    LDD #0
    STD RESULT
AND_END_81:
    LDD RESULT
    BEQ AND_FALSE_84
    LDD VAR_BRICK6
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_86
    LDD #0
    STD RESULT
    BRA CE_87
CT_86:
    LDD #1
    STD RESULT
CE_87:
    LDD RESULT
    BEQ AND_FALSE_84
    LDD #1
    STD RESULT
    BRA AND_END_85
AND_FALSE_84:
    LDD #0
    STD RESULT
AND_END_85:
    LDD RESULT
    LBEQ IF_END_22
    ; VPy_LINE:94
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK6
    STU TMPPTR
    STX ,U
    ; VPy_LINE:95
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:96
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:97
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_22
IF_END_22:
    LBRA IF_END_14
IF_NEXT_15:
IF_END_14:
    ; DEBUG: Statement 6 - Discriminant(7)
    ; VPy_LINE:100
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #95
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_90
    LDD #0
    STD RESULT
    BRA CE_91
CT_90:
    LDD #1
    STD RESULT
CE_91:
    LDD RESULT
    BEQ AND_FALSE_92
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #105
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_94
    LDD #0
    STD RESULT
    BRA CE_95
CT_94:
    LDD #1
    STD RESULT
CE_95:
    LDD RESULT
    BEQ AND_FALSE_92
    LDD #1
    STD RESULT
    BRA AND_END_93
AND_FALSE_92:
    LDD #0
    STD RESULT
AND_END_93:
    LDD RESULT
    LBEQ IF_NEXT_89
    ; VPy_LINE:101
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65416
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_98
    LDD #0
    STD RESULT
    BRA CE_99
CT_98:
    LDD #1
    STD RESULT
CE_99:
    LDD RESULT
    BEQ AND_FALSE_100
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_102
    LDD #0
    STD RESULT
    BRA CE_103
CT_102:
    LDD #1
    STD RESULT
CE_103:
    LDD RESULT
    BEQ AND_FALSE_100
    LDD #1
    STD RESULT
    BRA AND_END_101
AND_FALSE_100:
    LDD #0
    STD RESULT
AND_END_101:
    LDD RESULT
    BEQ AND_FALSE_104
    LDD VAR_BRICK7
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_106
    LDD #0
    STD RESULT
    BRA CE_107
CT_106:
    LDD #1
    STD RESULT
CE_107:
    LDD RESULT
    BEQ AND_FALSE_104
    LDD #1
    STD RESULT
    BRA AND_END_105
AND_FALSE_104:
    LDD #0
    STD RESULT
AND_END_105:
    LDD RESULT
    LBEQ IF_NEXT_97
    ; VPy_LINE:102
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK7
    STU TMPPTR
    STX ,U
    ; VPy_LINE:103
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:104
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:105
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_NEXT_97:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_109
    LDD #0
    STD RESULT
    BRA CE_110
CT_109:
    LDD #1
    STD RESULT
CE_110:
    LDD RESULT
    BEQ AND_FALSE_111
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_113
    LDD #0
    STD RESULT
    BRA CE_114
CT_113:
    LDD #1
    STD RESULT
CE_114:
    LDD RESULT
    BEQ AND_FALSE_111
    LDD #1
    STD RESULT
    BRA AND_END_112
AND_FALSE_111:
    LDD #0
    STD RESULT
AND_END_112:
    LDD RESULT
    BEQ AND_FALSE_115
    LDD VAR_BRICK8
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_117
    LDD #0
    STD RESULT
    BRA CE_118
CT_117:
    LDD #1
    STD RESULT
CE_118:
    LDD RESULT
    BEQ AND_FALSE_115
    LDD #1
    STD RESULT
    BRA AND_END_116
AND_FALSE_115:
    LDD #0
    STD RESULT
AND_END_116:
    LDD RESULT
    LBEQ IF_NEXT_108
    ; VPy_LINE:107
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK8
    STU TMPPTR
    STX ,U
    ; VPy_LINE:108
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:109
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:110
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_NEXT_108:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_120
    LDD #0
    STD RESULT
    BRA CE_121
CT_120:
    LDD #1
    STD RESULT
CE_121:
    LDD RESULT
    BEQ AND_FALSE_122
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_124
    LDD #0
    STD RESULT
    BRA CE_125
CT_124:
    LDD #1
    STD RESULT
CE_125:
    LDD RESULT
    BEQ AND_FALSE_122
    LDD #1
    STD RESULT
    BRA AND_END_123
AND_FALSE_122:
    LDD #0
    STD RESULT
AND_END_123:
    LDD RESULT
    BEQ AND_FALSE_126
    LDD VAR_BRICK9
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_128
    LDD #0
    STD RESULT
    BRA CE_129
CT_128:
    LDD #1
    STD RESULT
CE_129:
    LDD RESULT
    BEQ AND_FALSE_126
    LDD #1
    STD RESULT
    BRA AND_END_127
AND_FALSE_126:
    LDD #0
    STD RESULT
AND_END_127:
    LDD RESULT
    LBEQ IF_NEXT_119
    ; VPy_LINE:112
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK9
    STU TMPPTR
    STX ,U
    ; VPy_LINE:113
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:114
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:115
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_NEXT_119:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_131
    LDD #0
    STD RESULT
    BRA CE_132
CT_131:
    LDD #1
    STD RESULT
CE_132:
    LDD RESULT
    BEQ AND_FALSE_133
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_135
    LDD #0
    STD RESULT
    BRA CE_136
CT_135:
    LDD #1
    STD RESULT
CE_136:
    LDD RESULT
    BEQ AND_FALSE_133
    LDD #1
    STD RESULT
    BRA AND_END_134
AND_FALSE_133:
    LDD #0
    STD RESULT
AND_END_134:
    LDD RESULT
    BEQ AND_FALSE_137
    LDD VAR_BRICK10
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_139
    LDD #0
    STD RESULT
    BRA CE_140
CT_139:
    LDD #1
    STD RESULT
CE_140:
    LDD RESULT
    BEQ AND_FALSE_137
    LDD #1
    STD RESULT
    BRA AND_END_138
AND_FALSE_137:
    LDD #0
    STD RESULT
AND_END_138:
    LDD RESULT
    LBEQ IF_NEXT_130
    ; VPy_LINE:117
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK10
    STU TMPPTR
    STX ,U
    ; VPy_LINE:118
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:119
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:120
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_NEXT_130:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_142
    LDD #0
    STD RESULT
    BRA CE_143
CT_142:
    LDD #1
    STD RESULT
CE_143:
    LDD RESULT
    BEQ AND_FALSE_144
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_146
    LDD #0
    STD RESULT
    BRA CE_147
CT_146:
    LDD #1
    STD RESULT
CE_147:
    LDD RESULT
    BEQ AND_FALSE_144
    LDD #1
    STD RESULT
    BRA AND_END_145
AND_FALSE_144:
    LDD #0
    STD RESULT
AND_END_145:
    LDD RESULT
    BEQ AND_FALSE_148
    LDD VAR_BRICK11
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_150
    LDD #0
    STD RESULT
    BRA CE_151
CT_150:
    LDD #1
    STD RESULT
CE_151:
    LDD RESULT
    BEQ AND_FALSE_148
    LDD #1
    STD RESULT
    BRA AND_END_149
AND_FALSE_148:
    LDD #0
    STD RESULT
AND_END_149:
    LDD RESULT
    LBEQ IF_NEXT_141
    ; VPy_LINE:122
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK11
    STU TMPPTR
    STX ,U
    ; VPy_LINE:123
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:124
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:125
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_NEXT_141:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_152
    LDD #0
    STD RESULT
    BRA CE_153
CT_152:
    LDD #1
    STD RESULT
CE_153:
    LDD RESULT
    BEQ AND_FALSE_154
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #120
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_156
    LDD #0
    STD RESULT
    BRA CE_157
CT_156:
    LDD #1
    STD RESULT
CE_157:
    LDD RESULT
    BEQ AND_FALSE_154
    LDD #1
    STD RESULT
    BRA AND_END_155
AND_FALSE_154:
    LDD #0
    STD RESULT
AND_END_155:
    LDD RESULT
    BEQ AND_FALSE_158
    LDD VAR_BRICK12
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_160
    LDD #0
    STD RESULT
    BRA CE_161
CT_160:
    LDD #1
    STD RESULT
CE_161:
    LDD RESULT
    BEQ AND_FALSE_158
    LDD #1
    STD RESULT
    BRA AND_END_159
AND_FALSE_158:
    LDD #0
    STD RESULT
AND_END_159:
    LDD RESULT
    LBEQ IF_END_96
    ; VPy_LINE:127
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK12
    STU TMPPTR
    STX ,U
    ; VPy_LINE:128
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:129
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:130
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_96
IF_END_96:
    LBRA IF_END_88
IF_NEXT_89:
IF_END_88:
    ; DEBUG: Statement 7 - Discriminant(7)
    ; VPy_LINE:133
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #75
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_164
    LDD #0
    STD RESULT
    BRA CE_165
CT_164:
    LDD #1
    STD RESULT
CE_165:
    LDD RESULT
    BEQ AND_FALSE_166
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #85
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_168
    LDD #0
    STD RESULT
    BRA CE_169
CT_168:
    LDD #1
    STD RESULT
CE_169:
    LDD RESULT
    BEQ AND_FALSE_166
    LDD #1
    STD RESULT
    BRA AND_END_167
AND_FALSE_166:
    LDD #0
    STD RESULT
AND_END_167:
    LDD RESULT
    LBEQ IF_NEXT_163
    ; VPy_LINE:134
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65416
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_172
    LDD #0
    STD RESULT
    BRA CE_173
CT_172:
    LDD #1
    STD RESULT
CE_173:
    LDD RESULT
    BEQ AND_FALSE_174
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_176
    LDD #0
    STD RESULT
    BRA CE_177
CT_176:
    LDD #1
    STD RESULT
CE_177:
    LDD RESULT
    BEQ AND_FALSE_174
    LDD #1
    STD RESULT
    BRA AND_END_175
AND_FALSE_174:
    LDD #0
    STD RESULT
AND_END_175:
    LDD RESULT
    BEQ AND_FALSE_178
    LDD VAR_BRICK13
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_180
    LDD #0
    STD RESULT
    BRA CE_181
CT_180:
    LDD #1
    STD RESULT
CE_181:
    LDD RESULT
    BEQ AND_FALSE_178
    LDD #1
    STD RESULT
    BRA AND_END_179
AND_FALSE_178:
    LDD #0
    STD RESULT
AND_END_179:
    LDD RESULT
    LBEQ IF_NEXT_171
    ; VPy_LINE:135
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK13
    STU TMPPTR
    STX ,U
    ; VPy_LINE:136
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:137
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:138
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_NEXT_171:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65456
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_183
    LDD #0
    STD RESULT
    BRA CE_184
CT_183:
    LDD #1
    STD RESULT
CE_184:
    LDD RESULT
    BEQ AND_FALSE_185
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_187
    LDD #0
    STD RESULT
    BRA CE_188
CT_187:
    LDD #1
    STD RESULT
CE_188:
    LDD RESULT
    BEQ AND_FALSE_185
    LDD #1
    STD RESULT
    BRA AND_END_186
AND_FALSE_185:
    LDD #0
    STD RESULT
AND_END_186:
    LDD RESULT
    BEQ AND_FALSE_189
    LDD VAR_BRICK14
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_191
    LDD #0
    STD RESULT
    BRA CE_192
CT_191:
    LDD #1
    STD RESULT
CE_192:
    LDD RESULT
    BEQ AND_FALSE_189
    LDD #1
    STD RESULT
    BRA AND_END_190
AND_FALSE_189:
    LDD #0
    STD RESULT
AND_END_190:
    LDD RESULT
    LBEQ IF_NEXT_182
    ; VPy_LINE:140
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK14
    STU TMPPTR
    STX ,U
    ; VPy_LINE:141
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:142
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:143
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_NEXT_182:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #65496
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_194
    LDD #0
    STD RESULT
    BRA CE_195
CT_194:
    LDD #1
    STD RESULT
CE_195:
    LDD RESULT
    BEQ AND_FALSE_196
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_198
    LDD #0
    STD RESULT
    BRA CE_199
CT_198:
    LDD #1
    STD RESULT
CE_199:
    LDD RESULT
    BEQ AND_FALSE_196
    LDD #1
    STD RESULT
    BRA AND_END_197
AND_FALSE_196:
    LDD #0
    STD RESULT
AND_END_197:
    LDD RESULT
    BEQ AND_FALSE_200
    LDD VAR_BRICK15
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_202
    LDD #0
    STD RESULT
    BRA CE_203
CT_202:
    LDD #1
    STD RESULT
CE_203:
    LDD RESULT
    BEQ AND_FALSE_200
    LDD #1
    STD RESULT
    BRA AND_END_201
AND_FALSE_200:
    LDD #0
    STD RESULT
AND_END_201:
    LDD RESULT
    LBEQ IF_NEXT_193
    ; VPy_LINE:145
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK15
    STU TMPPTR
    STX ,U
    ; VPy_LINE:146
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:147
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:148
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_NEXT_193:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_205
    LDD #0
    STD RESULT
    BRA CE_206
CT_205:
    LDD #1
    STD RESULT
CE_206:
    LDD RESULT
    BEQ AND_FALSE_207
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_209
    LDD #0
    STD RESULT
    BRA CE_210
CT_209:
    LDD #1
    STD RESULT
CE_210:
    LDD RESULT
    BEQ AND_FALSE_207
    LDD #1
    STD RESULT
    BRA AND_END_208
AND_FALSE_207:
    LDD #0
    STD RESULT
AND_END_208:
    LDD RESULT
    BEQ AND_FALSE_211
    LDD VAR_BRICK16
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_213
    LDD #0
    STD RESULT
    BRA CE_214
CT_213:
    LDD #1
    STD RESULT
CE_214:
    LDD RESULT
    BEQ AND_FALSE_211
    LDD #1
    STD RESULT
    BRA AND_END_212
AND_FALSE_211:
    LDD #0
    STD RESULT
AND_END_212:
    LDD RESULT
    LBEQ IF_NEXT_204
    ; VPy_LINE:150
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK16
    STU TMPPTR
    STX ,U
    ; VPy_LINE:151
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:152
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:153
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_NEXT_204:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_216
    LDD #0
    STD RESULT
    BRA CE_217
CT_216:
    LDD #1
    STD RESULT
CE_217:
    LDD RESULT
    BEQ AND_FALSE_218
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_220
    LDD #0
    STD RESULT
    BRA CE_221
CT_220:
    LDD #1
    STD RESULT
CE_221:
    LDD RESULT
    BEQ AND_FALSE_218
    LDD #1
    STD RESULT
    BRA AND_END_219
AND_FALSE_218:
    LDD #0
    STD RESULT
AND_END_219:
    LDD RESULT
    BEQ AND_FALSE_222
    LDD VAR_BRICK17
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_224
    LDD #0
    STD RESULT
    BRA CE_225
CT_224:
    LDD #1
    STD RESULT
CE_225:
    LDD RESULT
    BEQ AND_FALSE_222
    LDD #1
    STD RESULT
    BRA AND_END_223
AND_FALSE_222:
    LDD #0
    STD RESULT
AND_END_223:
    LDD RESULT
    LBEQ IF_NEXT_215
    ; VPy_LINE:155
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK17
    STU TMPPTR
    STX ,U
    ; VPy_LINE:156
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:157
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:158
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_NEXT_215:
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_226
    LDD #0
    STD RESULT
    BRA CE_227
CT_226:
    LDD #1
    STD RESULT
CE_227:
    LDD RESULT
    BEQ AND_FALSE_228
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #120
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BLT CT_230
    LDD #0
    STD RESULT
    BRA CE_231
CT_230:
    LDD #1
    STD RESULT
CE_231:
    LDD RESULT
    BEQ AND_FALSE_228
    LDD #1
    STD RESULT
    BRA AND_END_229
AND_FALSE_228:
    LDD #0
    STD RESULT
AND_END_229:
    LDD RESULT
    BEQ AND_FALSE_232
    LDD VAR_BRICK18
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_234
    LDD #0
    STD RESULT
    BRA CE_235
CT_234:
    LDD #1
    STD RESULT
CE_235:
    LDD RESULT
    BEQ AND_FALSE_232
    LDD #1
    STD RESULT
    BRA AND_END_233
AND_FALSE_232:
    LDD #0
    STD RESULT
AND_END_233:
    LDD RESULT
    LBEQ IF_END_170
    ; VPy_LINE:160
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK18
    STU TMPPTR
    STX ,U
    ; VPy_LINE:161
    LDD #65533
    STD RESULT
    LDX RESULT
    LDU #VAR_BALL_VY
    STU TMPPTR
    STX ,U
    ; VPy_LINE:162
    LDD VAR_SCORE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:163
    LDD #10
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_170
IF_END_170:
    LBRA IF_END_162
IF_NEXT_163:
IF_END_162:
    ; DEBUG: Statement 8 - Discriminant(7)
    ; VPy_LINE:166
    LDD VAR_FLASH_TIMER
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGT CT_238
    LDD #0
    STD RESULT
    BRA CE_239
CT_238:
    LDD #1
    STD RESULT
CE_239:
    LDD RESULT
    LBEQ IF_NEXT_237
    ; VPy_LINE:167
    LDD VAR_FLASH_TIMER
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    ; VPy_LINE:168
    LDD #100
    STD RESULT
    LDX RESULT
    LDU #VAR_INTENSITY
    STU TMPPTR
    STX ,U
    LBRA IF_END_236
IF_NEXT_237:
    ; VPy_LINE:170
    LDD #70
    STD RESULT
    LDX RESULT
    LDU #VAR_INTENSITY
    STU TMPPTR
    STX ,U
IF_END_236:
    ; DEBUG: Statement 9 - Discriminant(7)
    ; VPy_LINE:174
    LDD VAR_BRICK1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_242
    LDD #0
    STD RESULT
    BRA CE_243
CT_242:
    LDD #1
    STD RESULT
CE_243:
    LDD RESULT
    LBEQ IF_NEXT_241
    ; VPy_LINE:175
    LDD #65416
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:176
    LDD #65456
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:177
    LDD #65456
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:178
    LDD #65416
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_240
IF_NEXT_241:
IF_END_240:
    ; DEBUG: Statement 10 - Discriminant(7)
    ; VPy_LINE:180
    LDD VAR_BRICK2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_246
    LDD #0
    STD RESULT
    BRA CE_247
CT_246:
    LDD #1
    STD RESULT
CE_247:
    LDD RESULT
    LBEQ IF_NEXT_245
    ; VPy_LINE:181
    LDD #65456
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:182
    LDD #65496
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:183
    LDD #65496
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:184
    LDD #65456
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_244
IF_NEXT_245:
IF_END_244:
    ; DEBUG: Statement 11 - Discriminant(7)
    ; VPy_LINE:186
    LDD VAR_BRICK3
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_250
    LDD #0
    STD RESULT
    BRA CE_251
CT_250:
    LDD #1
    STD RESULT
CE_251:
    LDD RESULT
    LBEQ IF_NEXT_249
    ; VPy_LINE:187
    LDD #65496
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:188
    LDD #0
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:189
    LDD #0
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:190
    LDD #65496
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_248
IF_NEXT_249:
IF_END_248:
    ; DEBUG: Statement 12 - Discriminant(7)
    ; VPy_LINE:192
    LDD VAR_BRICK4
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_254
    LDD #0
    STD RESULT
    BRA CE_255
CT_254:
    LDD #1
    STD RESULT
CE_255:
    LDD RESULT
    LBEQ IF_NEXT_253
    ; VPy_LINE:193
    LDD #0
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:194
    LDD #40
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:195
    LDD #40
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:196
    LDD #0
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_252
IF_NEXT_253:
IF_END_252:
    ; DEBUG: Statement 13 - Discriminant(7)
    ; VPy_LINE:198
    LDD VAR_BRICK5
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_258
    LDD #0
    STD RESULT
    BRA CE_259
CT_258:
    LDD #1
    STD RESULT
CE_259:
    LDD RESULT
    LBEQ IF_NEXT_257
    ; VPy_LINE:199
    LDD #40
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:200
    LDD #80
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:201
    LDD #80
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:202
    LDD #40
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_256
IF_NEXT_257:
IF_END_256:
    ; DEBUG: Statement 14 - Discriminant(7)
    ; VPy_LINE:204
    LDD VAR_BRICK6
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_262
    LDD #0
    STD RESULT
    BRA CE_263
CT_262:
    LDD #1
    STD RESULT
CE_263:
    LDD RESULT
    LBEQ IF_NEXT_261
    ; VPy_LINE:205
    LDD #80
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:206
    LDD #120
    STD VAR_ARG0
    LDD #115
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:207
    LDD #120
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #125
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:208
    LDD #80
    STD VAR_ARG0
    LDD #125
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #115
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_260
IF_NEXT_261:
IF_END_260:
    ; DEBUG: Statement 15 - Discriminant(7)
    ; VPy_LINE:211
    LDD VAR_BRICK7
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_266
    LDD #0
    STD RESULT
    BRA CE_267
CT_266:
    LDD #1
    STD RESULT
CE_267:
    LDD RESULT
    LBEQ IF_NEXT_265
    ; VPy_LINE:212
    LDD #65416
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:213
    LDD #65456
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:214
    LDD #65456
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:215
    LDD #65416
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_264
IF_NEXT_265:
IF_END_264:
    ; DEBUG: Statement 16 - Discriminant(7)
    ; VPy_LINE:217
    LDD VAR_BRICK8
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_270
    LDD #0
    STD RESULT
    BRA CE_271
CT_270:
    LDD #1
    STD RESULT
CE_271:
    LDD RESULT
    LBEQ IF_NEXT_269
    ; VPy_LINE:218
    LDD #65456
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:219
    LDD #65496
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:220
    LDD #65496
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:221
    LDD #65456
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_268
IF_NEXT_269:
IF_END_268:
    ; DEBUG: Statement 17 - Discriminant(7)
    ; VPy_LINE:223
    LDD VAR_BRICK9
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_274
    LDD #0
    STD RESULT
    BRA CE_275
CT_274:
    LDD #1
    STD RESULT
CE_275:
    LDD RESULT
    LBEQ IF_NEXT_273
    ; VPy_LINE:224
    LDD #65496
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:225
    LDD #0
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:226
    LDD #0
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:227
    LDD #65496
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_272
IF_NEXT_273:
IF_END_272:
    ; DEBUG: Statement 18 - Discriminant(7)
    ; VPy_LINE:229
    LDD VAR_BRICK10
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_278
    LDD #0
    STD RESULT
    BRA CE_279
CT_278:
    LDD #1
    STD RESULT
CE_279:
    LDD RESULT
    LBEQ IF_NEXT_277
    ; VPy_LINE:230
    LDD #0
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:231
    LDD #40
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:232
    LDD #40
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:233
    LDD #0
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_276
IF_NEXT_277:
IF_END_276:
    ; DEBUG: Statement 19 - Discriminant(7)
    ; VPy_LINE:235
    LDD VAR_BRICK11
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_282
    LDD #0
    STD RESULT
    BRA CE_283
CT_282:
    LDD #1
    STD RESULT
CE_283:
    LDD RESULT
    LBEQ IF_NEXT_281
    ; VPy_LINE:236
    LDD #40
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:237
    LDD #80
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:238
    LDD #80
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:239
    LDD #40
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_280
IF_NEXT_281:
IF_END_280:
    ; DEBUG: Statement 20 - Discriminant(7)
    ; VPy_LINE:241
    LDD VAR_BRICK12
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_286
    LDD #0
    STD RESULT
    BRA CE_287
CT_286:
    LDD #1
    STD RESULT
CE_287:
    LDD RESULT
    LBEQ IF_NEXT_285
    ; VPy_LINE:242
    LDD #80
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:243
    LDD #120
    STD VAR_ARG0
    LDD #95
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:244
    LDD #120
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #105
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:245
    LDD #80
    STD VAR_ARG0
    LDD #105
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #95
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_284
IF_NEXT_285:
IF_END_284:
    ; DEBUG: Statement 21 - Discriminant(7)
    ; VPy_LINE:248
    LDD VAR_BRICK13
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_290
    LDD #0
    STD RESULT
    BRA CE_291
CT_290:
    LDD #1
    STD RESULT
CE_291:
    LDD RESULT
    LBEQ IF_NEXT_289
    ; VPy_LINE:249
    LDD #65416
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:250
    LDD #65456
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:251
    LDD #65456
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:252
    LDD #65416
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65416
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_288
IF_NEXT_289:
IF_END_288:
    ; DEBUG: Statement 22 - Discriminant(7)
    ; VPy_LINE:254
    LDD VAR_BRICK14
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_294
    LDD #0
    STD RESULT
    BRA CE_295
CT_294:
    LDD #1
    STD RESULT
CE_295:
    LDD RESULT
    LBEQ IF_NEXT_293
    ; VPy_LINE:255
    LDD #65456
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:256
    LDD #65496
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:257
    LDD #65496
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:258
    LDD #65456
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65456
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_292
IF_NEXT_293:
IF_END_292:
    ; DEBUG: Statement 23 - Discriminant(7)
    ; VPy_LINE:260
    LDD VAR_BRICK15
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_298
    LDD #0
    STD RESULT
    BRA CE_299
CT_298:
    LDD #1
    STD RESULT
CE_299:
    LDD RESULT
    LBEQ IF_NEXT_297
    ; VPy_LINE:261
    LDD #65496
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:262
    LDD #0
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:263
    LDD #0
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:264
    LDD #65496
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #65496
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_296
IF_NEXT_297:
IF_END_296:
    ; DEBUG: Statement 24 - Discriminant(7)
    ; VPy_LINE:266
    LDD VAR_BRICK16
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_302
    LDD #0
    STD RESULT
    BRA CE_303
CT_302:
    LDD #1
    STD RESULT
CE_303:
    LDD RESULT
    LBEQ IF_NEXT_301
    ; VPy_LINE:267
    LDD #0
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:268
    LDD #40
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:269
    LDD #40
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:270
    LDD #0
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #0
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_300
IF_NEXT_301:
IF_END_300:
    ; DEBUG: Statement 25 - Discriminant(7)
    ; VPy_LINE:272
    LDD VAR_BRICK17
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_306
    LDD #0
    STD RESULT
    BRA CE_307
CT_306:
    LDD #1
    STD RESULT
CE_307:
    LDD RESULT
    LBEQ IF_NEXT_305
    ; VPy_LINE:273
    LDD #40
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:274
    LDD #80
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:275
    LDD #80
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:276
    LDD #40
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #40
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_304
IF_NEXT_305:
IF_END_304:
    ; DEBUG: Statement 26 - Discriminant(7)
    ; VPy_LINE:278
    LDD VAR_BRICK18
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_310
    LDD #0
    STD RESULT
    BRA CE_311
CT_310:
    LDD #1
    STD RESULT
CE_311:
    LDD RESULT
    LBEQ IF_NEXT_309
    ; VPy_LINE:279
    LDD #80
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:280
    LDD #120
    STD VAR_ARG0
    LDD #75
    STD VAR_ARG1
    LDD #120
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:281
    LDD #120
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #85
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; VPy_LINE:282
    LDD #80
    STD VAR_ARG0
    LDD #85
    STD VAR_ARG1
    LDD #80
    STD VAR_ARG2
    LDD #75
    STD VAR_ARG3
    LDD VAR_INTENSITY
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_308
IF_NEXT_309:
IF_END_308:
    ; DEBUG: Statement 27 - Discriminant(6)
    ; VPy_LINE:285
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #100
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 28 - Discriminant(6)
    ; VPy_LINE:286
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #100
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 29 - Discriminant(6)
    ; VPy_LINE:287
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #100
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 30 - Discriminant(6)
    ; VPy_LINE:288
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_BALL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_BALL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD #100
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 31 - Discriminant(6)
    ; VPy_LINE:291
    LDA #-127
    LDB #-127
    JSR Moveto_d
    LDA #$1E
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #0
    LDB #-2
    JSR Draw_Line_d
    ; DEBUG: Statement 32 - Discriminant(6)
    ; VPy_LINE:292
    LDA #-127
    LDB #127
    JSR Moveto_d
    LDA #$1E
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #-2
    LDB #0
    JSR Draw_Line_d
    ; DEBUG: Statement 33 - Discriminant(6)
    ; VPy_LINE:293
    LDA #127
    LDB #127
    JSR Moveto_d
    LDA #$1E
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #0
    LDB #2
    JSR Draw_Line_d
    ; DEBUG: Statement 34 - Discriminant(6)
    ; VPy_LINE:294
    LDA #127
    LDB #-127
    JSR Moveto_d
    LDA #$1E
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #2
    LDB #0
    JSR Draw_Line_d
    ; DEBUG: Statement 35 - Discriminant(7)
    ; VPy_LINE:297
    LDD VAR_BRICK1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_314
    LDD #0
    STD RESULT
    BRA CE_315
CT_314:
    LDD #1
    STD RESULT
CE_315:
    LDD RESULT
    BEQ AND_FALSE_316
    LDD VAR_BRICK2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_318
    LDD #0
    STD RESULT
    BRA CE_319
CT_318:
    LDD #1
    STD RESULT
CE_319:
    LDD RESULT
    BEQ AND_FALSE_316
    LDD #1
    STD RESULT
    BRA AND_END_317
AND_FALSE_316:
    LDD #0
    STD RESULT
AND_END_317:
    LDD RESULT
    BEQ AND_FALSE_320
    LDD VAR_BRICK3
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_322
    LDD #0
    STD RESULT
    BRA CE_323
CT_322:
    LDD #1
    STD RESULT
CE_323:
    LDD RESULT
    BEQ AND_FALSE_320
    LDD #1
    STD RESULT
    BRA AND_END_321
AND_FALSE_320:
    LDD #0
    STD RESULT
AND_END_321:
    LDD RESULT
    BEQ AND_FALSE_324
    LDD VAR_BRICK4
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_326
    LDD #0
    STD RESULT
    BRA CE_327
CT_326:
    LDD #1
    STD RESULT
CE_327:
    LDD RESULT
    BEQ AND_FALSE_324
    LDD #1
    STD RESULT
    BRA AND_END_325
AND_FALSE_324:
    LDD #0
    STD RESULT
AND_END_325:
    LDD RESULT
    BEQ AND_FALSE_328
    LDD VAR_BRICK5
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_330
    LDD #0
    STD RESULT
    BRA CE_331
CT_330:
    LDD #1
    STD RESULT
CE_331:
    LDD RESULT
    BEQ AND_FALSE_328
    LDD #1
    STD RESULT
    BRA AND_END_329
AND_FALSE_328:
    LDD #0
    STD RESULT
AND_END_329:
    LDD RESULT
    BEQ AND_FALSE_332
    LDD VAR_BRICK6
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_334
    LDD #0
    STD RESULT
    BRA CE_335
CT_334:
    LDD #1
    STD RESULT
CE_335:
    LDD RESULT
    BEQ AND_FALSE_332
    LDD #1
    STD RESULT
    BRA AND_END_333
AND_FALSE_332:
    LDD #0
    STD RESULT
AND_END_333:
    LDD RESULT
    BEQ AND_FALSE_336
    LDD VAR_BRICK7
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_338
    LDD #0
    STD RESULT
    BRA CE_339
CT_338:
    LDD #1
    STD RESULT
CE_339:
    LDD RESULT
    BEQ AND_FALSE_336
    LDD #1
    STD RESULT
    BRA AND_END_337
AND_FALSE_336:
    LDD #0
    STD RESULT
AND_END_337:
    LDD RESULT
    BEQ AND_FALSE_340
    LDD VAR_BRICK8
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_342
    LDD #0
    STD RESULT
    BRA CE_343
CT_342:
    LDD #1
    STD RESULT
CE_343:
    LDD RESULT
    BEQ AND_FALSE_340
    LDD #1
    STD RESULT
    BRA AND_END_341
AND_FALSE_340:
    LDD #0
    STD RESULT
AND_END_341:
    LDD RESULT
    BEQ AND_FALSE_344
    LDD VAR_BRICK9
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_346
    LDD #0
    STD RESULT
    BRA CE_347
CT_346:
    LDD #1
    STD RESULT
CE_347:
    LDD RESULT
    BEQ AND_FALSE_344
    LDD #1
    STD RESULT
    BRA AND_END_345
AND_FALSE_344:
    LDD #0
    STD RESULT
AND_END_345:
    LDD RESULT
    BEQ AND_FALSE_348
    LDD VAR_BRICK10
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_350
    LDD #0
    STD RESULT
    BRA CE_351
CT_350:
    LDD #1
    STD RESULT
CE_351:
    LDD RESULT
    BEQ AND_FALSE_348
    LDD #1
    STD RESULT
    BRA AND_END_349
AND_FALSE_348:
    LDD #0
    STD RESULT
AND_END_349:
    LDD RESULT
    BEQ AND_FALSE_352
    LDD VAR_BRICK11
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_354
    LDD #0
    STD RESULT
    BRA CE_355
CT_354:
    LDD #1
    STD RESULT
CE_355:
    LDD RESULT
    BEQ AND_FALSE_352
    LDD #1
    STD RESULT
    BRA AND_END_353
AND_FALSE_352:
    LDD #0
    STD RESULT
AND_END_353:
    LDD RESULT
    BEQ AND_FALSE_356
    LDD VAR_BRICK12
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_358
    LDD #0
    STD RESULT
    BRA CE_359
CT_358:
    LDD #1
    STD RESULT
CE_359:
    LDD RESULT
    BEQ AND_FALSE_356
    LDD #1
    STD RESULT
    BRA AND_END_357
AND_FALSE_356:
    LDD #0
    STD RESULT
AND_END_357:
    LDD RESULT
    BEQ AND_FALSE_360
    LDD VAR_BRICK13
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_362
    LDD #0
    STD RESULT
    BRA CE_363
CT_362:
    LDD #1
    STD RESULT
CE_363:
    LDD RESULT
    BEQ AND_FALSE_360
    LDD #1
    STD RESULT
    BRA AND_END_361
AND_FALSE_360:
    LDD #0
    STD RESULT
AND_END_361:
    LDD RESULT
    BEQ AND_FALSE_364
    LDD VAR_BRICK14
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_366
    LDD #0
    STD RESULT
    BRA CE_367
CT_366:
    LDD #1
    STD RESULT
CE_367:
    LDD RESULT
    BEQ AND_FALSE_364
    LDD #1
    STD RESULT
    BRA AND_END_365
AND_FALSE_364:
    LDD #0
    STD RESULT
AND_END_365:
    LDD RESULT
    BEQ AND_FALSE_368
    LDD VAR_BRICK15
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_370
    LDD #0
    STD RESULT
    BRA CE_371
CT_370:
    LDD #1
    STD RESULT
CE_371:
    LDD RESULT
    BEQ AND_FALSE_368
    LDD #1
    STD RESULT
    BRA AND_END_369
AND_FALSE_368:
    LDD #0
    STD RESULT
AND_END_369:
    LDD RESULT
    BEQ AND_FALSE_372
    LDD VAR_BRICK16
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_374
    LDD #0
    STD RESULT
    BRA CE_375
CT_374:
    LDD #1
    STD RESULT
CE_375:
    LDD RESULT
    BEQ AND_FALSE_372
    LDD #1
    STD RESULT
    BRA AND_END_373
AND_FALSE_372:
    LDD #0
    STD RESULT
AND_END_373:
    LDD RESULT
    BEQ AND_FALSE_376
    LDD VAR_BRICK17
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_378
    LDD #0
    STD RESULT
    BRA CE_379
CT_378:
    LDD #1
    STD RESULT
CE_379:
    LDD RESULT
    BEQ AND_FALSE_376
    LDD #1
    STD RESULT
    BRA AND_END_377
AND_FALSE_376:
    LDD #0
    STD RESULT
AND_END_377:
    LDD RESULT
    BEQ AND_FALSE_380
    LDD VAR_BRICK18
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_382
    LDD #0
    STD RESULT
    BRA CE_383
CT_382:
    LDD #1
    STD RESULT
CE_383:
    LDD RESULT
    BEQ AND_FALSE_380
    LDD #1
    STD RESULT
    BRA AND_END_381
AND_FALSE_380:
    LDD #0
    STD RESULT
AND_END_381:
    LDD RESULT
    LBEQ IF_NEXT_313
    ; VPy_LINE:299
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK1
    STU TMPPTR
    STX ,U
    ; VPy_LINE:300
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK2
    STU TMPPTR
    STX ,U
    ; VPy_LINE:301
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK3
    STU TMPPTR
    STX ,U
    ; VPy_LINE:302
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK4
    STU TMPPTR
    STX ,U
    ; VPy_LINE:303
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK5
    STU TMPPTR
    STX ,U
    ; VPy_LINE:304
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK6
    STU TMPPTR
    STX ,U
    ; VPy_LINE:305
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK7
    STU TMPPTR
    STX ,U
    ; VPy_LINE:306
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK8
    STU TMPPTR
    STX ,U
    ; VPy_LINE:307
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK9
    STU TMPPTR
    STX ,U
    ; VPy_LINE:308
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK10
    STU TMPPTR
    STX ,U
    ; VPy_LINE:309
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK11
    STU TMPPTR
    STX ,U
    ; VPy_LINE:310
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK12
    STU TMPPTR
    STX ,U
    ; VPy_LINE:311
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK13
    STU TMPPTR
    STX ,U
    ; VPy_LINE:312
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK14
    STU TMPPTR
    STX ,U
    ; VPy_LINE:313
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK15
    STU TMPPTR
    STX ,U
    ; VPy_LINE:314
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK16
    STU TMPPTR
    STX ,U
    ; VPy_LINE:315
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK17
    STU TMPPTR
    STX ,U
    ; VPy_LINE:316
    LDD #1
    STD RESULT
    LDX RESULT
    LDU #VAR_BRICK18
    STU TMPPTR
    STX ,U
    ; VPy_LINE:317
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_SCORE
    STU TMPPTR
    STX ,U
    ; VPy_LINE:318
    LDD #20
    STD RESULT
    LDX RESULT
    LDU #VAR_FLASH_TIMER
    STU TMPPTR
    STX ,U
    LBRA IF_END_312
IF_NEXT_313:
IF_END_312:
    RTS

; DRAW_LINE unified wrapper - handles 16-bit signed coordinates correctly
; Args: (x0,y0,x1,y1,intensity) as 16-bit words, treating x/y as signed bytes.
; ALWAYS sets intensity and handles Reset0Ref properly.
DRAW_LINE_WRAPPER:
    ; Set DP to hardware registers
    LDA #$D0
    TFR A,DP
    ; ALWAYS set intensity (no optimization)
    LDA VAR_ARG4+1
    JSR Intensity_a
    ; CRITICAL: Reset integrator origin before each line
    JSR Reset0Ref
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DX_CLAMP_HI_OK
    LDD #127
DLW_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DX_CLAMP_LO_OK
    LDD #-128
DLW_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DY_CLAMP_HI_OK
    LDD #127
DLW_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DY_CLAMP_LO_OK
    LDD #-128
DLW_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLW_DX_HI_OK
    LDA #63
DLW_DX_HI_OK: CMPA #-64
    BGE DLW_DX_LO_OK
    LDA #-64
DLW_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLW_DY_HI_OK
    LDA #63
DLW_DY_HI_OK: CMPA #-64
    BGE DLW_DY_LO_OK
    LDA #-64
DLW_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS

; DRAW_LINE_FAST - optimized version that skips redundant setup
; Use this for multiple consecutive draws with same intensity
; Args: (x0,y0,x1,y1) only - intensity must be set beforehand
DRAW_LINE_FAST:
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DX_CLAMP_HI_OK
    LDD #127
DLF_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DX_CLAMP_LO_OK
    LDD #-128
DLF_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DY_CLAMP_HI_OK
    LDD #127
DLF_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DY_CLAMP_LO_OK
    LDD #-128
DLF_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLF_DX_HI_OK
    LDA #63
DLF_DX_HI_OK: CMPA #-64
    BGE DLF_DX_LO_OK
    LDA #-64
DLF_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLF_DY_HI_OK
    LDA #63
DLF_DY_HI_OK: CMPA #-64
    BGE DLF_DY_LO_OK
    LDA #-64
DLF_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
TMPLEFT   EQU RESULT+2
TMPRIGHT  EQU RESULT+4
TMPPTR    EQU RESULT+6
VAR_BALL_VX EQU $CF00+0
VAR_BALL_VY EQU $CF00+2
VAR_BALL_X EQU $CF00+4
VAR_BALL_Y EQU $CF00+6
VAR_BRICK1 EQU $CF00+8
VAR_BRICK10 EQU $CF00+10
VAR_BRICK11 EQU $CF00+12
VAR_BRICK12 EQU $CF00+14
VAR_BRICK13 EQU $CF00+16
VAR_BRICK14 EQU $CF00+18
VAR_BRICK15 EQU $CF00+20
VAR_BRICK16 EQU $CF00+22
VAR_BRICK17 EQU $CF00+24
VAR_BRICK18 EQU $CF00+26
VAR_BRICK2 EQU $CF00+28
VAR_BRICK3 EQU $CF00+30
VAR_BRICK4 EQU $CF00+32
VAR_BRICK5 EQU $CF00+34
VAR_BRICK6 EQU $CF00+36
VAR_BRICK7 EQU $CF00+38
VAR_BRICK8 EQU $CF00+40
VAR_BRICK9 EQU $CF00+42
VAR_FLASH_TIMER EQU $CF00+44
VAR_INTENSITY EQU $CF00+46
VAR_SCORE EQU $CF00+48
; Call argument scratch space
VAR_ARG0 EQU RESULT+26
VAR_ARG1 EQU RESULT+28
VAR_ARG2 EQU RESULT+30
VAR_ARG3 EQU RESULT+32
VAR_ARG4 EQU RESULT+34
VLINE_DX EQU RESULT+50
VLINE_DY EQU RESULT+51
VLINE_STEPS EQU RESULT+52
VLINE_LIST EQU RESULT+53
