; --- Motorola 6809 backend (Vectrex) title='FRACTAL_TREE' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8
    FCB $50
    FCB $20
    FCB $BB
    FCC "FRACTAL TREE"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

    ; *** DEBUG *** main() function code inline (initialization)
    LDD #4
    STD VAR_TREE_DEPTH
    LDD #50
    STD VAR_BASE_LENGTH
    LDD #25
    STD VAR_ANGLE_DELTA
    LDD #0
    STD VAR_ANIMATION_FRAME
    LDD #120
    STD VAR_INTENSITY_
    LDD #100
    STD VAR_SCALE_FACTOR
    LDD #0
    STD VAR_ANGLE_OFFSET
    ; VPy_LINE:17
    LDD #4
    STD RESULT
    LDX RESULT
    LDU #VAR_TREE_DEPTH
    STU TMPPTR
    STX ,U
    ; VPy_LINE:18
    LDD #50
    STD RESULT
    LDX RESULT
    LDU #VAR_BASE_LENGTH
    STU TMPPTR
    STX ,U
    ; VPy_LINE:19
    LDD #25
    STD RESULT
    LDX RESULT
    LDU #VAR_ANGLE_DELTA
    STU TMPPTR
    STX ,U
    ; VPy_LINE:20
    LDD #120
    STD RESULT
    LDX RESULT
    LDU #VAR_INTENSITY_
    STU TMPPTR
    STX ,U

MAIN:
    JSR Wait_Recal
    LDA #$80
    STA VIA_t1_cnt_lo
    ; *** Call loop() as subroutine (executed every frame)
    JSR LOOP_BODY
    BRA MAIN

LOOP_BODY:
    ; DEBUG: Processing 100 statements in loop() body
    ; DEBUG: Statement 0 - Discriminant(0)
    ; VPy_LINE:24
    LDD VAR_ANIMATION_FRAME
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_ANIMATION_FRAME
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 1 - Discriminant(7)
    ; VPy_LINE:25
    LDD VAR_ANIMATION_FRAME
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #360
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BGE CT_2
    LDD #0
    STD RESULT
    BRA CE_3
CT_2:
    LDD #1
    STD RESULT
CE_3:
    LDD RESULT
    LBEQ IF_NEXT_1
    ; VPy_LINE:26
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_ANIMATION_FRAME
    STU TMPPTR
    STX ,U
    LBRA IF_END_0
IF_NEXT_1:
IF_END_0:
    ; DEBUG: Statement 2 - Discriminant(0)
    ; VPy_LINE:29
    LDD VAR_ANIMATION_FRAME
    STD RESULT
    LDD RESULT
    ASLB
    ROLA
    STD RESULT
    LDX RESULT
    LDU #VAR_ANGLE_OFFSET
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 3 - Discriminant(0)
    ; VPy_LINE:30
    LDD #80
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANIMATION_FRAME
    STD RESULT
    LDD RESULT
    ASLB
    ROLA
    ASLB
    ROLA
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #20
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SCALE_FACTOR
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 4 - Discriminant(6)
    ; VPy_LINE:33
    LDA #-120
    LDB #-120
    JSR Moveto_d
    LDA #$3C
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #0
    LDB #-16
    JSR Draw_Line_d
    ; DEBUG: Statement 5 - Discriminant(6)
    ; VPy_LINE:34
    LDA #-120
    LDB #120
    JSR Moveto_d
    LDA #$3C
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #-16
    LDB #0
    JSR Draw_Line_d
    ; DEBUG: Statement 6 - Discriminant(6)
    ; VPy_LINE:35
    LDA #120
    LDB #120
    JSR Moveto_d
    LDA #$3C
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #0
    LDB #16
    JSR Draw_Line_d
    ; DEBUG: Statement 7 - Discriminant(6)
    ; VPy_LINE:36
    LDA #120
    LDB #-120
    JSR Moveto_d
    LDA #$3C
    JSR Intensity_a
    CLR Vec_Misc_Count
    LDA #16
    LDB #0
    JSR Draw_Line_d
    ; DEBUG: Statement 8 - Discriminant(1)
    ; VPy_LINE:40
    LDD #0
    STD RESULT
    ; DEBUG: Statement 9 - Discriminant(1)
    ; VPy_LINE:41
    LDD #65476
    STD RESULT
    ; DEBUG: Statement 10 - Discriminant(1)
    ; VPy_LINE:42
    LDD #0
    STD RESULT
    ; DEBUG: Statement 11 - Discriminant(1)
    ; VPy_LINE:43
    LDD VAR_Y1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BASE_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 12 - Discriminant(6)
    ; VPy_LINE:44
    LDD VAR_X1
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y1
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 13 - Discriminant(1)
    ; VPy_LINE:47
    LDD VAR_BASE_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #70
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD #100
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 14 - Discriminant(1)
    ; VPy_LINE:48
    LDD #270
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    ADDD RESULT
    STD RESULT
    ; DEBUG: Statement 15 - Discriminant(1)
    ; VPy_LINE:49
    CLRA
    CLRB
    STD RESULT
    ; DEBUG: Statement 16 - Discriminant(1)
    ; VPy_LINE:52
    LDD VAR_ANGLE1_LEFT
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 17 - Discriminant(1)
    ; VPy_LINE:53
    LDD VAR_ANGLE1_LEFT
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 18 - Discriminant(1)
    ; VPy_LINE:54
    LDD VAR_X2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS1_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 19 - Discriminant(1)
    ; VPy_LINE:55
    LDD VAR_Y2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN1_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 20 - Discriminant(6)
    ; VPy_LINE:56
    LDD VAR_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #20
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 21 - Discriminant(1)
    ; VPy_LINE:59
    LDD VAR_ANGLE1_RIGHT
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 22 - Discriminant(1)
    ; VPy_LINE:60
    LDD VAR_ANGLE1_RIGHT
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 23 - Discriminant(1)
    ; VPy_LINE:61
    LDD VAR_X2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS1_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 24 - Discriminant(1)
    ; VPy_LINE:62
    LDD VAR_Y2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN1_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 25 - Discriminant(6)
    ; VPy_LINE:63
    LDD VAR_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #20
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 26 - Discriminant(1)
    ; VPy_LINE:66
    LDD VAR_LENGTH1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD #100
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 27 - Discriminant(1)
    ; VPy_LINE:69
    LDD VAR_ANGLE1_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 28 - Discriminant(1)
    ; VPy_LINE:70
    LDD VAR_ANGLE1_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 29 - Discriminant(1)
    ; VPy_LINE:72
    LDD VAR_ANGLE2_LL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 30 - Discriminant(1)
    ; VPy_LINE:73
    LDD VAR_ANGLE2_LL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 31 - Discriminant(1)
    ; VPy_LINE:74
    LDD VAR_X2_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS2_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 32 - Discriminant(1)
    ; VPy_LINE:75
    LDD VAR_Y2_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN2_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 33 - Discriminant(6)
    ; VPy_LINE:76
    LDD VAR_X2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 34 - Discriminant(1)
    ; VPy_LINE:78
    LDD VAR_ANGLE2_LR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 35 - Discriminant(1)
    ; VPy_LINE:79
    LDD VAR_ANGLE2_LR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 36 - Discriminant(1)
    ; VPy_LINE:80
    LDD VAR_X2_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS2_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 37 - Discriminant(1)
    ; VPy_LINE:81
    LDD VAR_Y2_LEFT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN2_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 38 - Discriminant(6)
    ; VPy_LINE:82
    LDD VAR_X2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2_LEFT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 39 - Discriminant(1)
    ; VPy_LINE:85
    LDD VAR_ANGLE1_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 40 - Discriminant(1)
    ; VPy_LINE:86
    LDD VAR_ANGLE1_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 41 - Discriminant(1)
    ; VPy_LINE:88
    LDD VAR_ANGLE2_RL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 42 - Discriminant(1)
    ; VPy_LINE:89
    LDD VAR_ANGLE2_RL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 43 - Discriminant(1)
    ; VPy_LINE:90
    LDD VAR_X2_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS2_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 44 - Discriminant(1)
    ; VPy_LINE:91
    LDD VAR_Y2_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN2_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 45 - Discriminant(6)
    ; VPy_LINE:92
    LDD VAR_X2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 46 - Discriminant(1)
    ; VPy_LINE:94
    LDD VAR_ANGLE2_RR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 47 - Discriminant(1)
    ; VPy_LINE:95
    LDD VAR_ANGLE2_RR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 48 - Discriminant(1)
    ; VPy_LINE:96
    LDD VAR_X2_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS2_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 49 - Discriminant(1)
    ; VPy_LINE:97
    LDD VAR_Y2_RIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN2_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 50 - Discriminant(6)
    ; VPy_LINE:98
    LDD VAR_X2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y2_RIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #40
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 51 - Discriminant(1)
    ; VPy_LINE:101
    LDD VAR_LENGTH2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #50
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD #100
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 52 - Discriminant(1)
    ; VPy_LINE:104
    LDD VAR_ANGLE2_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 53 - Discriminant(1)
    ; VPy_LINE:105
    LDD VAR_ANGLE2_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 54 - Discriminant(1)
    ; VPy_LINE:107
    LDD VAR_ANGLE3_LLL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 55 - Discriminant(1)
    ; VPy_LINE:108
    LDD VAR_ANGLE3_LLL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 56 - Discriminant(1)
    ; VPy_LINE:109
    LDD VAR_X3_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_LLL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 57 - Discriminant(1)
    ; VPy_LINE:110
    LDD VAR_Y3_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_LLL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 58 - Discriminant(6)
    ; VPy_LINE:111
    LDD VAR_X3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_LLL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_LLL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 59 - Discriminant(1)
    ; VPy_LINE:113
    LDD VAR_ANGLE3_LLR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 60 - Discriminant(1)
    ; VPy_LINE:114
    LDD VAR_ANGLE3_LLR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 61 - Discriminant(1)
    ; VPy_LINE:115
    LDD VAR_X3_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_LLR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 62 - Discriminant(1)
    ; VPy_LINE:116
    LDD VAR_Y3_LL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_LLR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 63 - Discriminant(6)
    ; VPy_LINE:117
    LDD VAR_X3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_LL
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_LLR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_LLR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 64 - Discriminant(1)
    ; VPy_LINE:120
    LDD VAR_ANGLE2_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 65 - Discriminant(1)
    ; VPy_LINE:121
    LDD VAR_ANGLE2_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 66 - Discriminant(1)
    ; VPy_LINE:123
    LDD VAR_ANGLE3_LRL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 67 - Discriminant(1)
    ; VPy_LINE:124
    LDD VAR_ANGLE3_LRL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 68 - Discriminant(1)
    ; VPy_LINE:125
    LDD VAR_X3_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_LRL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 69 - Discriminant(1)
    ; VPy_LINE:126
    LDD VAR_Y3_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_LRL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 70 - Discriminant(6)
    ; VPy_LINE:127
    LDD VAR_X3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_LRL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_LRL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 71 - Discriminant(1)
    ; VPy_LINE:129
    LDD VAR_ANGLE3_LRR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 72 - Discriminant(1)
    ; VPy_LINE:130
    LDD VAR_ANGLE3_LRR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 73 - Discriminant(1)
    ; VPy_LINE:131
    LDD VAR_X3_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_LRR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 74 - Discriminant(1)
    ; VPy_LINE:132
    LDD VAR_Y3_LR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_LRR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 75 - Discriminant(6)
    ; VPy_LINE:133
    LDD VAR_X3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_LR
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_LRR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_LRR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 76 - Discriminant(1)
    ; VPy_LINE:136
    LDD VAR_ANGLE2_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 77 - Discriminant(1)
    ; VPy_LINE:137
    LDD VAR_ANGLE2_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 78 - Discriminant(1)
    ; VPy_LINE:139
    LDD VAR_ANGLE3_RLL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 79 - Discriminant(1)
    ; VPy_LINE:140
    LDD VAR_ANGLE3_RLL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 80 - Discriminant(1)
    ; VPy_LINE:141
    LDD VAR_X3_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_RLL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 81 - Discriminant(1)
    ; VPy_LINE:142
    LDD VAR_Y3_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_RLL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 82 - Discriminant(6)
    ; VPy_LINE:143
    LDD VAR_X3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_RLL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_RLL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 83 - Discriminant(1)
    ; VPy_LINE:145
    LDD VAR_ANGLE3_RLR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 84 - Discriminant(1)
    ; VPy_LINE:146
    LDD VAR_ANGLE3_RLR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 85 - Discriminant(1)
    ; VPy_LINE:147
    LDD VAR_X3_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_RLR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 86 - Discriminant(1)
    ; VPy_LINE:148
    LDD VAR_Y3_RL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_RLR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 87 - Discriminant(6)
    ; VPy_LINE:149
    LDD VAR_X3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_RL
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_RLR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_RLR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 88 - Discriminant(1)
    ; VPy_LINE:152
    LDD VAR_ANGLE2_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 89 - Discriminant(1)
    ; VPy_LINE:153
    LDD VAR_ANGLE2_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_DELTA
    STD RESULT
    LDD RESULT
    LSRA
    RORB
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 90 - Discriminant(1)
    ; VPy_LINE:155
    LDD VAR_ANGLE3_RRL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 91 - Discriminant(1)
    ; VPy_LINE:156
    LDD VAR_ANGLE3_RRL
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 92 - Discriminant(1)
    ; VPy_LINE:157
    LDD VAR_X3_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_RRL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 93 - Discriminant(1)
    ; VPy_LINE:158
    LDD VAR_Y3_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_RRL
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 94 - Discriminant(6)
    ; VPy_LINE:159
    LDD VAR_X3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_RRL
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_RRL
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 95 - Discriminant(1)
    ; VPy_LINE:161
    LDD VAR_ANGLE3_RRR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 96 - Discriminant(1)
    ; VPy_LINE:162
    LDD VAR_ANGLE3_RRR
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 97 - Discriminant(1)
    ; VPy_LINE:163
    LDD VAR_X3_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_COS3_RRR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 98 - Discriminant(1)
    ; VPy_LINE:164
    LDD VAR_Y3_RR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SIN3_RRR
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LENGTH3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 99 - Discriminant(6)
    ; VPy_LINE:165
    LDD VAR_X3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_Y3_RR
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_X4_RRR
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_Y4_RRR
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_INTENSITY_
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #60
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    RTS

MUL16:
    LDD MUL_A
    STD MUL_RES
    LDD #0
    STD MUL_TMP
    LDD MUL_B
    STD MUL_CNT
MUL16_LOOP:
    LDD MUL_CNT
    BEQ MUL16_DONE
    LDD MUL_CNT
    ANDA #1
    BEQ MUL16_SKIP
    LDD MUL_RES
    ADDD MUL_TMP
    STD MUL_TMP
MUL16_SKIP:
    LDD MUL_RES
    ASLB
    ROLA
    STD MUL_RES
    LDD MUL_CNT
    LSRA
    RORB
    STD MUL_CNT
    BRA MUL16_LOOP
MUL16_DONE:
    LDD MUL_TMP
    STD RESULT
    RTS

DIV16:
    LDD #0
    STD DIV_Q
    LDD DIV_A
    STD DIV_R
    LDD DIV_B
    BEQ DIV16_DONE
DIV16_LOOP:
    LDD DIV_R
    SUBD DIV_B
    BLO DIV16_DONE
    STD DIV_R
    LDD DIV_Q
    ADDD #1
    STD DIV_Q
    BRA DIV16_LOOP
DIV16_DONE:
    LDD DIV_Q
    STD RESULT
    RTS

; DRAW_LINE unified wrapper - handles 16-bit signed coordinates correctly
; Args: (x0,y0,x1,y1,intensity) as 16-bit words, treating x/y as signed bytes.
; ALWAYS sets intensity and handles Reset0Ref properly.
DRAW_LINE_WRAPPER:
    ; Set DP to hardware registers
    LDA #$D0
    TFR A,DP
    ; ALWAYS set intensity (no optimization)
    LDA VAR_ARG4+1
    JSR Intensity_a
    ; CRITICAL: Reset integrator origin before each line
    JSR Reset0Ref
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DX_CLAMP_HI_OK
    LDD #127
DLW_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DX_CLAMP_LO_OK
    LDD #-128
DLW_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DY_CLAMP_HI_OK
    LDD #127
DLW_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DY_CLAMP_LO_OK
    LDD #-128
DLW_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLW_DX_HI_OK
    LDA #63
DLW_DX_HI_OK: CMPA #-64
    BGE DLW_DX_LO_OK
    LDA #-64
DLW_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLW_DY_HI_OK
    LDA #63
DLW_DY_HI_OK: CMPA #-64
    BGE DLW_DY_LO_OK
    LDA #-64
DLW_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS

; DRAW_LINE_FAST - optimized version that skips redundant setup
; Use this for multiple consecutive draws with same intensity
; Args: (x0,y0,x1,y1) only - intensity must be set beforehand
DRAW_LINE_FAST:
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DX_CLAMP_HI_OK
    LDD #127
DLF_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DX_CLAMP_LO_OK
    LDD #-128
DLF_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DY_CLAMP_HI_OK
    LDD #127
DLF_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DY_CLAMP_LO_OK
    LDD #-128
DLF_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLF_DX_HI_OK
    LDA #63
DLF_DX_HI_OK: CMPA #-64
    BGE DLF_DX_LO_OK
    LDA #-64
DLF_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLF_DY_HI_OK
    LDA #63
DLF_DY_HI_OK: CMPA #-64
    BGE DLF_DY_LO_OK
    LDA #-64
DLF_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
TMPLEFT   EQU RESULT+2
TMPRIGHT  EQU RESULT+4
TMPPTR    EQU RESULT+6
MUL_A    EQU RESULT+8
MUL_B    EQU RESULT+10
MUL_RES  EQU RESULT+12
MUL_TMP  EQU RESULT+14
MUL_CNT  EQU RESULT+16
DIV_A   EQU RESULT+18
DIV_B   EQU RESULT+20
DIV_Q   EQU RESULT+22
DIV_R   EQU RESULT+24
VAR_ANGLE1_LEFT EQU $CF00+0
VAR_ANGLE1_RIGHT EQU $CF00+2
VAR_ANGLE2_LL EQU $CF00+4
VAR_ANGLE2_LR EQU $CF00+6
VAR_ANGLE2_RL EQU $CF00+8
VAR_ANGLE2_RR EQU $CF00+10
VAR_ANGLE3_LLL EQU $CF00+12
VAR_ANGLE3_LLR EQU $CF00+14
VAR_ANGLE3_LRL EQU $CF00+16
VAR_ANGLE3_LRR EQU $CF00+18
VAR_ANGLE3_RLL EQU $CF00+20
VAR_ANGLE3_RLR EQU $CF00+22
VAR_ANGLE3_RRL EQU $CF00+24
VAR_ANGLE3_RRR EQU $CF00+26
VAR_ANGLE_DELTA EQU $CF00+28
VAR_ANGLE_OFFSET EQU $CF00+30
VAR_ANIMATION_FRAME EQU $CF00+32
VAR_BASE_LENGTH EQU $CF00+34
VAR_COS1_LEFT EQU $CF00+36
VAR_COS1_RIGHT EQU $CF00+38
VAR_COS2_LL EQU $CF00+40
VAR_COS2_LR EQU $CF00+42
VAR_COS2_RL EQU $CF00+44
VAR_COS2_RR EQU $CF00+46
VAR_COS3_LLL EQU $CF00+48
VAR_COS3_LLR EQU $CF00+50
VAR_COS3_LRL EQU $CF00+52
VAR_COS3_LRR EQU $CF00+54
VAR_COS3_RLL EQU $CF00+56
VAR_COS3_RLR EQU $CF00+58
VAR_COS3_RRL EQU $CF00+60
VAR_COS3_RRR EQU $CF00+62
VAR_INTENSITY_ EQU $CF00+64
VAR_LENGTH1 EQU $CF00+66
VAR_LENGTH2 EQU $CF00+68
VAR_LENGTH3 EQU $CF00+70
VAR_SCALE_FACTOR EQU $CF00+72
VAR_SIN1_LEFT EQU $CF00+74
VAR_SIN1_RIGHT EQU $CF00+76
VAR_SIN2_LL EQU $CF00+78
VAR_SIN2_LR EQU $CF00+80
VAR_SIN2_RL EQU $CF00+82
VAR_SIN2_RR EQU $CF00+84
VAR_SIN3_LLL EQU $CF00+86
VAR_SIN3_LLR EQU $CF00+88
VAR_SIN3_LRL EQU $CF00+90
VAR_SIN3_LRR EQU $CF00+92
VAR_SIN3_RLL EQU $CF00+94
VAR_SIN3_RLR EQU $CF00+96
VAR_SIN3_RRL EQU $CF00+98
VAR_SIN3_RRR EQU $CF00+100
VAR_TREE_DEPTH EQU $CF00+102
VAR_X1 EQU $CF00+104
VAR_X2 EQU $CF00+106
VAR_X2_LEFT EQU $CF00+108
VAR_X2_RIGHT EQU $CF00+110
VAR_X3_LL EQU $CF00+112
VAR_X3_LR EQU $CF00+114
VAR_X3_RL EQU $CF00+116
VAR_X3_RR EQU $CF00+118
VAR_X4_LLL EQU $CF00+120
VAR_X4_LLR EQU $CF00+122
VAR_X4_LRL EQU $CF00+124
VAR_X4_LRR EQU $CF00+126
VAR_X4_RLL EQU $CF00+128
VAR_X4_RLR EQU $CF00+130
VAR_X4_RRL EQU $CF00+132
VAR_X4_RRR EQU $CF00+134
VAR_Y1 EQU $CF00+136
VAR_Y2 EQU $CF00+138
VAR_Y2_LEFT EQU $CF00+140
VAR_Y2_RIGHT EQU $CF00+142
VAR_Y3_LL EQU $CF00+144
VAR_Y3_LR EQU $CF00+146
VAR_Y3_RL EQU $CF00+148
VAR_Y3_RR EQU $CF00+150
VAR_Y4_LLL EQU $CF00+152
VAR_Y4_LLR EQU $CF00+154
VAR_Y4_LRL EQU $CF00+156
VAR_Y4_LRR EQU $CF00+158
VAR_Y4_RLL EQU $CF00+160
VAR_Y4_RLR EQU $CF00+162
VAR_Y4_RRL EQU $CF00+164
VAR_Y4_RRR EQU $CF00+166
; Call argument scratch space
VAR_ARG0 EQU RESULT+26
VAR_ARG1 EQU RESULT+28
VAR_ARG2 EQU RESULT+30
VAR_ARG3 EQU RESULT+32
VAR_ARG4 EQU RESULT+34
VLINE_DX EQU RESULT+168
VLINE_DY EQU RESULT+169
VLINE_STEPS EQU RESULT+170
VLINE_LIST EQU RESULT+171
; Trig tables (shared)
SIN_TABLE:
    FDB 0
    FDB 6
    FDB 12
    FDB 19
    FDB 25
    FDB 31
    FDB 37
    FDB 43
    FDB 49
    FDB 54
    FDB 60
    FDB 65
    FDB 71
    FDB 76
    FDB 81
    FDB 85
    FDB 90
    FDB 94
    FDB 98
    FDB 102
    FDB 106
    FDB 109
    FDB 112
    FDB 115
    FDB 117
    FDB 120
    FDB 122
    FDB 123
    FDB 125
    FDB 126
    FDB 126
    FDB 127
    FDB 127
    FDB 127
    FDB 126
    FDB 126
    FDB 125
    FDB 123
    FDB 122
    FDB 120
    FDB 117
    FDB 115
    FDB 112
    FDB 109
    FDB 106
    FDB 102
    FDB 98
    FDB 94
    FDB 90
    FDB 85
    FDB 81
    FDB 76
    FDB 71
    FDB 65
    FDB 60
    FDB 54
    FDB 49
    FDB 43
    FDB 37
    FDB 31
    FDB 25
    FDB 19
    FDB 12
    FDB 6
    FDB 0
    FDB -6
    FDB -12
    FDB -19
    FDB -25
    FDB -31
    FDB -37
    FDB -43
    FDB -49
    FDB -54
    FDB -60
    FDB -65
    FDB -71
    FDB -76
    FDB -81
    FDB -85
    FDB -90
    FDB -94
    FDB -98
    FDB -102
    FDB -106
    FDB -109
    FDB -112
    FDB -115
    FDB -117
    FDB -120
    FDB -122
    FDB -123
    FDB -125
    FDB -126
    FDB -126
    FDB -127
    FDB -127
    FDB -127
    FDB -126
    FDB -126
    FDB -125
    FDB -123
    FDB -122
    FDB -120
    FDB -117
    FDB -115
    FDB -112
    FDB -109
    FDB -106
    FDB -102
    FDB -98
    FDB -94
    FDB -90
    FDB -85
    FDB -81
    FDB -76
    FDB -71
    FDB -65
    FDB -60
    FDB -54
    FDB -49
    FDB -43
    FDB -37
    FDB -31
    FDB -25
    FDB -19
    FDB -12
    FDB -6
COS_TABLE:
    FDB 127
    FDB 127
    FDB 126
    FDB 126
    FDB 125
    FDB 123
    FDB 122
    FDB 120
    FDB 117
    FDB 115
    FDB 112
    FDB 109
    FDB 106
    FDB 102
    FDB 98
    FDB 94
    FDB 90
    FDB 85
    FDB 81
    FDB 76
    FDB 71
    FDB 65
    FDB 60
    FDB 54
    FDB 49
    FDB 43
    FDB 37
    FDB 31
    FDB 25
    FDB 19
    FDB 12
    FDB 6
    FDB 0
    FDB -6
    FDB -12
    FDB -19
    FDB -25
    FDB -31
    FDB -37
    FDB -43
    FDB -49
    FDB -54
    FDB -60
    FDB -65
    FDB -71
    FDB -76
    FDB -81
    FDB -85
    FDB -90
    FDB -94
    FDB -98
    FDB -102
    FDB -106
    FDB -109
    FDB -112
    FDB -115
    FDB -117
    FDB -120
    FDB -122
    FDB -123
    FDB -125
    FDB -126
    FDB -126
    FDB -127
    FDB -127
    FDB -127
    FDB -126
    FDB -126
    FDB -125
    FDB -123
    FDB -122
    FDB -120
    FDB -117
    FDB -115
    FDB -112
    FDB -109
    FDB -106
    FDB -102
    FDB -98
    FDB -94
    FDB -90
    FDB -85
    FDB -81
    FDB -76
    FDB -71
    FDB -65
    FDB -60
    FDB -54
    FDB -49
    FDB -43
    FDB -37
    FDB -31
    FDB -25
    FDB -19
    FDB -12
    FDB -6
    FDB 0
    FDB 6
    FDB 12
    FDB 19
    FDB 25
    FDB 31
    FDB 37
    FDB 43
    FDB 49
    FDB 54
    FDB 60
    FDB 65
    FDB 71
    FDB 76
    FDB 81
    FDB 85
    FDB 90
    FDB 94
    FDB 98
    FDB 102
    FDB 106
    FDB 109
    FDB 112
    FDB 115
    FDB 117
    FDB 120
    FDB 122
    FDB 123
    FDB 125
    FDB 126
    FDB 126
    FDB 127
TAN_TABLE:
    FDB 0
    FDB 1
    FDB 2
    FDB 3
    FDB 4
    FDB 5
    FDB 6
    FDB 7
    FDB 8
    FDB 9
    FDB 11
    FDB 12
    FDB 13
    FDB 15
    FDB 16
    FDB 18
    FDB 20
    FDB 22
    FDB 24
    FDB 27
    FDB 30
    FDB 33
    FDB 37
    FDB 42
    FDB 48
    FDB 56
    FDB 66
    FDB 80
    FDB 101
    FDB 120
    FDB 120
    FDB 120
    FDB -120
    FDB -120
    FDB -120
    FDB -120
    FDB -101
    FDB -80
    FDB -66
    FDB -56
    FDB -48
    FDB -42
    FDB -37
    FDB -33
    FDB -30
    FDB -27
    FDB -24
    FDB -22
    FDB -20
    FDB -18
    FDB -16
    FDB -15
    FDB -13
    FDB -12
    FDB -11
    FDB -9
    FDB -8
    FDB -7
    FDB -6
    FDB -5
    FDB -4
    FDB -3
    FDB -2
    FDB -1
    FDB 0
    FDB 1
    FDB 2
    FDB 3
    FDB 4
    FDB 5
    FDB 6
    FDB 7
    FDB 8
    FDB 9
    FDB 11
    FDB 12
    FDB 13
    FDB 15
    FDB 16
    FDB 18
    FDB 20
    FDB 22
    FDB 24
    FDB 27
    FDB 30
    FDB 33
    FDB 37
    FDB 42
    FDB 48
    FDB 56
    FDB 66
    FDB 80
    FDB 101
    FDB 120
    FDB 120
    FDB 120
    FDB -120
    FDB -120
    FDB -120
    FDB -120
    FDB -101
    FDB -80
    FDB -66
    FDB -56
    FDB -48
    FDB -42
    FDB -37
    FDB -33
    FDB -30
    FDB -27
    FDB -24
    FDB -22
    FDB -20
    FDB -18
    FDB -16
    FDB -15
    FDB -13
    FDB -12
    FDB -11
    FDB -9
    FDB -8
    FDB -7
    FDB -6
    FDB -5
    FDB -4
    FDB -3
    FDB -2
    FDB -1
