; --- Motorola 6809 backend (Vectrex) title='FRACTAL_TREE_IMPROVED' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8
    FCB $50
    FCB $20
    FCB $BB
    FCC "FRACTAL TREE IMPROVED"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

    ; *** DEBUG *** main() function code inline (initialization)
    LDD #0
    STD VAR_FRAME_COUNTER
    LDD #5
    STD VAR_TREE_DEPTH
    LDD #60
    STD VAR_BASE_LENGTH
    LDD #30
    STD VAR_ANGLE_SPREAD
    LDD #127
    STD VAR_BRIGHTNESS
    LDD #0
    STD RESULT
    LDX RESULT
    LDU #VAR_FRAME_COUNTER
    STU TMPPTR
    STX ,U
    LDD #5
    STD RESULT
    LDX RESULT
    LDU #VAR_TREE_DEPTH
    STU TMPPTR
    STX ,U
    LDD #60
    STD RESULT
    LDX RESULT
    LDU #VAR_BASE_LENGTH
    STU TMPPTR
    STX ,U
    LDD #30
    STD RESULT
    LDX RESULT
    LDU #VAR_ANGLE_SPREAD
    STU TMPPTR
    STX ,U
    LDD #127
    STD RESULT
    LDX RESULT
    LDU #VAR_BRIGHTNESS
    STU TMPPTR
    STX ,U

MAIN:
    JSR Wait_Recal
    LDA #$80
    STA VIA_t1_cnt_lo
    ; *** Call loop() as subroutine (executed every frame)
    JSR LOOP_BODY
    BRA MAIN

LOOP_BODY:
    ; DEBUG: Processing 92 statements in loop() body
    ; DEBUG: Statement 0 - Discriminant(0)
    LDD VAR_FRAME_COUNTER
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_FRAME_COUNTER
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 1 - Discriminant(0)
    LDD VAR_FRAME_COUNTER
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #360
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; quotient in RESULT, need remainder: A - Q*B
    LDD DIV_A
    STD TMPLEFT
    LDD RESULT
    STD MUL_A
    LDD DIV_B
    STD MUL_B
    JSR MUL16
    ; product in RESULT, subtract from original A (TMPLEFT)
    LDD TMPLEFT
    SUBD RESULT
    STD RESULT
    LDX RESULT
    LDU #VAR_FRAME_COUNTER
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 2 - Discriminant(1)
    LDD VAR_FRAME_COUNTER
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #6
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 3 - Discriminant(1)
    LDD #100
    STD RESULT
    ; DEBUG: Statement 4 - Discriminant(1)
    LDD VAR_FRAME_COUNTER
    STD RESULT
    LDD RESULT
    ASLB
    ROLA
    ASLB
    ROLA
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 5 - Discriminant(1)
    LDD VAR_BRIGHTNESS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; DEBUG: Statement 6 - Discriminant(6)
    LDD #65436
    STD VAR_ARG0
    LDD #65436
    STD VAR_ARG1
    LDD #100
    STD VAR_ARG2
    LDD #65436
    STD VAR_ARG3
    LDD VAR_BORDER_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 7 - Discriminant(6)
    LDD #100
    STD VAR_ARG0
    LDD #65436
    STD VAR_ARG1
    LDD #100
    STD VAR_ARG2
    LDD #100
    STD VAR_ARG3
    LDD VAR_BORDER_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 8 - Discriminant(6)
    LDD #100
    STD VAR_ARG0
    LDD #100
    STD VAR_ARG1
    LDD #65436
    STD VAR_ARG2
    LDD #100
    STD VAR_ARG3
    LDD VAR_BORDER_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 9 - Discriminant(6)
    LDD #65436
    STD VAR_ARG0
    LDD #100
    STD VAR_ARG1
    LDD #65436
    STD VAR_ARG2
    LDD #65436
    STD VAR_ARG3
    LDD VAR_BORDER_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 10 - Discriminant(1)
    LDD #0
    STD RESULT
    ; DEBUG: Statement 11 - Discriminant(1)
    LDD #65466
    STD RESULT
    ; DEBUG: Statement 12 - Discriminant(1)
    LDD #0
    STD RESULT
    ; DEBUG: Statement 13 - Discriminant(1)
    LDD VAR_TRUNK_Y1
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BASE_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 14 - Discriminant(6)
    LDD VAR_TRUNK_X1
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRUNK_Y1
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_TRUNK_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_TRUNK_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_BRIGHTNESS
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 15 - Discriminant(1)
    LDD VAR_BASE_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    ; DEBUG: Statement 16 - Discriminant(0)
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #4
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDX RESULT
    LDU #VAR_BRANCH_LENGTH
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 17 - Discriminant(1)
    LDD #270
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_VARIATION
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 18 - Discriminant(1)
    LDD #270
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_VARIATION
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 19 - Discriminant(1)
    LDD VAR_LEFT_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 20 - Discriminant(1)
    LDD VAR_LEFT_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 21 - Discriminant(1)
    LDD VAR_TRUNK_X2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LEFT_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 22 - Discriminant(1)
    LDD VAR_TRUNK_Y2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LEFT_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 23 - Discriminant(1)
    LDD VAR_BRIGHTNESS
    STD RESULT
    ; DEBUG: Statement 24 - Discriminant(0)
    LDD VAR_BRANCH_BRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #25
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_BRANCH_BRIGHT
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 25 - Discriminant(6)
    LDD VAR_TRUNK_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRUNK_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LEFT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LEFT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_BRANCH_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 26 - Discriminant(1)
    LDD VAR_RIGHT_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 27 - Discriminant(1)
    LDD VAR_RIGHT_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 28 - Discriminant(1)
    LDD VAR_TRUNK_X2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RIGHT_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 29 - Discriminant(1)
    LDD VAR_TRUNK_Y2
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RIGHT_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 30 - Discriminant(6)
    LDD VAR_TRUNK_X2
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_TRUNK_Y2
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RIGHT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RIGHT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_BRANCH_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 31 - Discriminant(1)
    LDD VAR_BRANCH_LENGTH
    STD RESULT
    ; DEBUG: Statement 32 - Discriminant(0)
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #3
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDX RESULT
    LDU #VAR_SUB_LENGTH
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 33 - Discriminant(0)
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #5
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDX RESULT
    LDU #VAR_SUB_LENGTH
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 34 - Discriminant(1)
    LDD VAR_LEFT_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 35 - Discriminant(1)
    LDD VAR_LEFT_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 36 - Discriminant(1)
    LDD VAR_LL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 37 - Discriminant(1)
    LDD VAR_LL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 38 - Discriminant(1)
    LDD VAR_LEFT_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LL_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 39 - Discriminant(1)
    LDD VAR_LEFT_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LL_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 40 - Discriminant(1)
    LDD VAR_BRANCH_BRIGHT
    STD RESULT
    ; DEBUG: Statement 41 - Discriminant(0)
    LDD VAR_SUB_BRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #20
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_SUB_BRIGHT
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 42 - Discriminant(6)
    LDD VAR_LEFT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LEFT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_SUB_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 43 - Discriminant(1)
    LDD VAR_LR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 44 - Discriminant(1)
    LDD VAR_LR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 45 - Discriminant(1)
    LDD VAR_LEFT_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LR_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 46 - Discriminant(1)
    LDD VAR_LEFT_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LR_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 47 - Discriminant(6)
    LDD VAR_LEFT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LEFT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_SUB_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 48 - Discriminant(1)
    LDD VAR_RIGHT_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 49 - Discriminant(1)
    LDD VAR_RIGHT_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 50 - Discriminant(1)
    LDD VAR_RL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 51 - Discriminant(1)
    LDD VAR_RL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 52 - Discriminant(1)
    LDD VAR_RIGHT_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RL_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 53 - Discriminant(1)
    LDD VAR_RIGHT_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RL_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 54 - Discriminant(6)
    LDD VAR_RIGHT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RIGHT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_SUB_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 55 - Discriminant(1)
    LDD VAR_RR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 56 - Discriminant(1)
    LDD VAR_RR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 57 - Discriminant(1)
    LDD VAR_RIGHT_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RR_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 58 - Discriminant(1)
    LDD VAR_RIGHT_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RR_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SUB_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 59 - Discriminant(6)
    LDD VAR_RIGHT_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RIGHT_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_SUB_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 60 - Discriminant(1)
    LDD VAR_SUB_LENGTH
    STD RESULT
    ; DEBUG: Statement 61 - Discriminant(0)
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDX RESULT
    LDU #VAR_FINAL_LENGTH
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 62 - Discriminant(1)
    LDD VAR_SUB_BRIGHT
    STD RESULT
    ; DEBUG: Statement 63 - Discriminant(0)
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #15
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_FINAL_BRIGHT
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 64 - Discriminant(1)
    LDD VAR_LL_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 65 - Discriminant(1)
    LDD VAR_LL_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 66 - Discriminant(1)
    LDD VAR_LLL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 67 - Discriminant(1)
    LDD VAR_LLL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 68 - Discriminant(1)
    LDD VAR_LL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LLL_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 69 - Discriminant(1)
    LDD VAR_LL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LLL_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 70 - Discriminant(6)
    LDD VAR_LL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LLL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LLL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 71 - Discriminant(1)
    LDD VAR_LLR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 72 - Discriminant(1)
    LDD VAR_LLR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 73 - Discriminant(1)
    LDD VAR_LL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LLR_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 74 - Discriminant(1)
    LDD VAR_LL_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_LLR_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 75 - Discriminant(6)
    LDD VAR_LL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LLR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LLR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 76 - Discriminant(1)
    LDD VAR_RR_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 77 - Discriminant(1)
    LDD VAR_RR_ANGLE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_ANGLE_SPREAD
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 78 - Discriminant(1)
    LDD VAR_RRL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 79 - Discriminant(1)
    LDD VAR_RRL_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 80 - Discriminant(1)
    LDD VAR_RR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RRL_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 81 - Discriminant(1)
    LDD VAR_RR_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RRL_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 82 - Discriminant(6)
    LDD VAR_RR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RRL_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RRL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 83 - Discriminant(1)
    LDD VAR_RRR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    LDX #COS_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 84 - Discriminant(1)
    LDD VAR_RRR_ANGLE
    STD RESULT
    LDD RESULT
    ANDB #$7F
    CLRA
    ASLB
    ROLA
    LDX #SIN_TABLE
    ABX
    LDD ,X
    STD RESULT
    ; DEBUG: Statement 85 - Discriminant(1)
    LDD VAR_RR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RRR_COS
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 86 - Discriminant(1)
    LDD VAR_RR_Y
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_RRR_SIN
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD VAR_FINAL_LENGTH
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD MUL_A
    LDD TMPRIGHT
    STD MUL_B
    JSR MUL16
    LDD RESULT
    STD TMPLEFT
    LDD VAR_SCALE_FACTOR
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    ; DEBUG: Statement 87 - Discriminant(6)
    LDD VAR_RR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RRR_X
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RRR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    ; DEBUG: Statement 88 - Discriminant(1)
    LDD VAR_FRAME_COUNTER
    STD RESULT
    ; DEBUG: Statement 89 - Discriminant(0)
    LDD VAR_LEAF_FRAME
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #10
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDX RESULT
    LDU #VAR_LEAF_FRAME
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 90 - Discriminant(0)
    LDD VAR_LEAF_FRAME
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #4
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    ; quotient in RESULT, need remainder: A - Q*B
    LDD DIV_A
    STD TMPLEFT
    LDD RESULT
    STD MUL_A
    LDD DIV_B
    STD MUL_B
    JSR MUL16
    ; product in RESULT, subtract from original A (TMPLEFT)
    LDD TMPLEFT
    SUBD RESULT
    STD RESULT
    LDX RESULT
    LDU #VAR_LEAF_FRAME
    STU TMPPTR
    STX ,U
    ; DEBUG: Statement 91 - Discriminant(7)
    LDD VAR_LEAF_FRAME
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #0
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    BEQ CT_2
    LDD #0
    STD RESULT
    BRA CE_3
CT_2:
    LDD #1
    STD RESULT
CE_3:
    LDD RESULT
    LBEQ IF_NEXT_1
    LDD VAR_FINAL_BRIGHT
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    STD DIV_A
    LDD TMPRIGHT
    STD DIV_B
    JSR DIV16
    LDD VAR_LLL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LLL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LLL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LLL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_LEAF_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LDD VAR_LLR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_LLR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_LLR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_LLR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_LEAF_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LDD VAR_RRL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RRL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RRL_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RRL_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_LEAF_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LDD VAR_RRR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD VAR_RRR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDD VAR_RRR_X
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #2
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG2
    LDD VAR_RRR_Y
    STD RESULT
    LDD RESULT
    STD VAR_ARG3
    LDD VAR_LEAF_BRIGHT
    STD RESULT
    LDD RESULT
    STD VAR_ARG4
    JSR DRAW_LINE_WRAPPER
    LDD #0
    STD RESULT
    LBRA IF_END_0
IF_NEXT_1:
IF_END_0:
    RTS

MUL16:
    LDD MUL_A
    STD MUL_RES
    LDD #0
    STD MUL_TMP
    LDD MUL_B
    STD MUL_CNT
MUL16_LOOP:
    LDD MUL_CNT
    BEQ MUL16_DONE
    LDD MUL_CNT
    ANDA #1
    BEQ MUL16_SKIP
    LDD MUL_RES
    ADDD MUL_TMP
    STD MUL_TMP
MUL16_SKIP:
    LDD MUL_RES
    ASLB
    ROLA
    STD MUL_RES
    LDD MUL_CNT
    LSRA
    RORB
    STD MUL_CNT
    BRA MUL16_LOOP
MUL16_DONE:
    LDD MUL_TMP
    STD RESULT
    RTS

DIV16:
    LDD #0
    STD DIV_Q
    LDD DIV_A
    STD DIV_R
    LDD DIV_B
    BEQ DIV16_DONE
DIV16_LOOP:
    LDD DIV_R
    SUBD DIV_B
    BLO DIV16_DONE
    STD DIV_R
    LDD DIV_Q
    ADDD #1
    STD DIV_Q
    BRA DIV16_LOOP
DIV16_DONE:
    LDD DIV_Q
    STD RESULT
    RTS

; DRAW_LINE unified wrapper - handles 16-bit signed coordinates correctly
; Args: (x0,y0,x1,y1,intensity) as 16-bit words, treating x/y as signed bytes.
; ALWAYS sets intensity and handles Reset0Ref properly.
DRAW_LINE_WRAPPER:
    ; Set DP to hardware registers
    LDA #$D0
    TFR A,DP
    ; ALWAYS set intensity (no optimization)
    LDA VAR_ARG4+1
    JSR Intensity_a
    ; CRITICAL: Reset integrator origin before each line
    JSR Reset0Ref
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DX_CLAMP_HI_OK
    LDD #127
DLW_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DX_CLAMP_LO_OK
    LDD #-128
DLW_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLW_DY_CLAMP_HI_OK
    LDD #127
DLW_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLW_DY_CLAMP_LO_OK
    LDD #-128
DLW_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLW_DX_HI_OK
    LDA #63
DLW_DX_HI_OK: CMPA #-64
    BGE DLW_DX_LO_OK
    LDA #-64
DLW_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLW_DY_HI_OK
    LDA #63
DLW_DY_HI_OK: CMPA #-64
    BGE DLW_DY_LO_OK
    LDA #-64
DLW_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS

; DRAW_LINE_FAST - optimized version that skips redundant setup
; Use this for multiple consecutive draws with same intensity
; Args: (x0,y0,x1,y1) only - intensity must be set beforehand
DRAW_LINE_FAST:
    ; Move to start (y in A, x in B) - use signed byte values
    LDA VAR_ARG1+1  ; Y start (signed byte)
    LDB VAR_ARG0+1  ; X start (signed byte)
    JSR Moveto_d
    ; Compute deltas using 16-bit arithmetic, then clamp to signed bytes
    ; dx = x1 - x0 (treating as signed)
    LDD VAR_ARG2    ; x1 (16-bit)
    SUBD VAR_ARG0   ; subtract x0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DX_CLAMP_HI_OK
    LDD #127
DLF_DX_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DX_CLAMP_LO_OK
    LDD #-128
DLF_DX_CLAMP_LO_OK:
    STB VLINE_DX    ; Store dx as signed byte
    ; dy = y1 - y0 (treating as signed)
    LDD VAR_ARG3    ; y1 (16-bit)
    SUBD VAR_ARG1   ; subtract y0 (16-bit)
    ; Clamp D to signed byte range (-128 to +127)
    CMPD #127
    BLE DLF_DY_CLAMP_HI_OK
    LDD #127
DLF_DY_CLAMP_HI_OK:
    CMPD #-128
    BGE DLF_DY_CLAMP_LO_OK
    LDD #-128
DLF_DY_CLAMP_LO_OK:
    STB VLINE_DY    ; Store dy as signed byte
    ; Further clamp to Vectrex hardware limits (-64 to +63)
    LDA VLINE_DX
    CMPA #63
    BLE DLF_DX_HI_OK
    LDA #63
DLF_DX_HI_OK: CMPA #-64
    BGE DLF_DX_LO_OK
    LDA #-64
DLF_DX_LO_OK: STA VLINE_DX
    ; Clamp dy to Vectrex limits
    LDA VLINE_DY
    CMPA #63
    BLE DLF_DY_HI_OK
    LDA #63
DLF_DY_HI_OK: CMPA #-64
    BGE DLF_DY_LO_OK
    LDA #-64
DLF_DY_LO_OK: STA VLINE_DY
    ; Clear Vec_Misc_Count for proper timing
    CLR Vec_Misc_Count
    ; Draw line (A=dy, B=dx)
    LDA VLINE_DY
    LDB VLINE_DX
    JSR Draw_Line_d
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
TMPLEFT   EQU RESULT+2
TMPRIGHT  EQU RESULT+4
TMPPTR    EQU RESULT+6
MUL_A    EQU RESULT+8
MUL_B    EQU RESULT+10
MUL_RES  EQU RESULT+12
MUL_TMP  EQU RESULT+14
MUL_CNT  EQU RESULT+16
DIV_A   EQU RESULT+18
DIV_B   EQU RESULT+20
DIV_Q   EQU RESULT+22
DIV_R   EQU RESULT+24
VAR_ANGLE_SPREAD EQU $C900+0
VAR_ANGLE_VARIATION EQU $C900+2
VAR_BASE_LENGTH EQU $C900+4
VAR_BORDER_BRIGHT EQU $C900+6
VAR_BRANCH_BRIGHT EQU $C900+8
VAR_BRANCH_LENGTH EQU $C900+10
VAR_BRIGHTNESS EQU $C900+12
VAR_FINAL_BRIGHT EQU $C900+14
VAR_FINAL_LENGTH EQU $C900+16
VAR_FRAME_COUNTER EQU $C900+18
VAR_LEAF_BRIGHT EQU $C900+20
VAR_LEAF_FRAME EQU $C900+22
VAR_LEFT_ANGLE EQU $C900+24
VAR_LEFT_COS EQU $C900+26
VAR_LEFT_SIN EQU $C900+28
VAR_LEFT_X EQU $C900+30
VAR_LEFT_Y EQU $C900+32
VAR_LL_ANGLE EQU $C900+34
VAR_LL_COS EQU $C900+36
VAR_LL_SIN EQU $C900+38
VAR_LL_X EQU $C900+40
VAR_LL_Y EQU $C900+42
VAR_LLL_ANGLE EQU $C900+44
VAR_LLL_COS EQU $C900+46
VAR_LLL_SIN EQU $C900+48
VAR_LLL_X EQU $C900+50
VAR_LLL_Y EQU $C900+52
VAR_LLR_ANGLE EQU $C900+54
VAR_LLR_COS EQU $C900+56
VAR_LLR_SIN EQU $C900+58
VAR_LLR_X EQU $C900+60
VAR_LLR_Y EQU $C900+62
VAR_LR_ANGLE EQU $C900+64
VAR_LR_COS EQU $C900+66
VAR_LR_SIN EQU $C900+68
VAR_LR_X EQU $C900+70
VAR_LR_Y EQU $C900+72
VAR_RIGHT_ANGLE EQU $C900+74
VAR_RIGHT_COS EQU $C900+76
VAR_RIGHT_SIN EQU $C900+78
VAR_RIGHT_X EQU $C900+80
VAR_RIGHT_Y EQU $C900+82
VAR_RL_ANGLE EQU $C900+84
VAR_RL_COS EQU $C900+86
VAR_RL_SIN EQU $C900+88
VAR_RL_X EQU $C900+90
VAR_RL_Y EQU $C900+92
VAR_RR_ANGLE EQU $C900+94
VAR_RR_COS EQU $C900+96
VAR_RR_SIN EQU $C900+98
VAR_RR_X EQU $C900+100
VAR_RR_Y EQU $C900+102
VAR_RRL_ANGLE EQU $C900+104
VAR_RRL_COS EQU $C900+106
VAR_RRL_SIN EQU $C900+108
VAR_RRL_X EQU $C900+110
VAR_RRL_Y EQU $C900+112
VAR_RRR_ANGLE EQU $C900+114
VAR_RRR_COS EQU $C900+116
VAR_RRR_SIN EQU $C900+118
VAR_RRR_X EQU $C900+120
VAR_RRR_Y EQU $C900+122
VAR_SCALE_FACTOR EQU $C900+124
VAR_SUB_BRIGHT EQU $C900+126
VAR_SUB_LENGTH EQU $C900+128
VAR_TREE_DEPTH EQU $C900+130
VAR_TRUNK_X1 EQU $C900+132
VAR_TRUNK_X2 EQU $C900+134
VAR_TRUNK_Y1 EQU $C900+136
VAR_TRUNK_Y2 EQU $C900+138
; Call argument scratch space
VAR_ARG0 EQU RESULT+26
VAR_ARG1 EQU RESULT+28
VAR_ARG2 EQU RESULT+30
VAR_ARG3 EQU RESULT+32
VAR_ARG4 EQU RESULT+34
VLINE_DX EQU RESULT+140
VLINE_DY EQU RESULT+141
VLINE_STEPS EQU RESULT+142
VLINE_LIST EQU RESULT+143
; Trig tables (shared)
SIN_TABLE:
    FDB 0
    FDB 6
    FDB 12
    FDB 19
    FDB 25
    FDB 31
    FDB 37
    FDB 43
    FDB 49
    FDB 54
    FDB 60
    FDB 65
    FDB 71
    FDB 76
    FDB 81
    FDB 85
    FDB 90
    FDB 94
    FDB 98
    FDB 102
    FDB 106
    FDB 109
    FDB 112
    FDB 115
    FDB 117
    FDB 120
    FDB 122
    FDB 123
    FDB 125
    FDB 126
    FDB 126
    FDB 127
    FDB 127
    FDB 127
    FDB 126
    FDB 126
    FDB 125
    FDB 123
    FDB 122
    FDB 120
    FDB 117
    FDB 115
    FDB 112
    FDB 109
    FDB 106
    FDB 102
    FDB 98
    FDB 94
    FDB 90
    FDB 85
    FDB 81
    FDB 76
    FDB 71
    FDB 65
    FDB 60
    FDB 54
    FDB 49
    FDB 43
    FDB 37
    FDB 31
    FDB 25
    FDB 19
    FDB 12
    FDB 6
    FDB 0
    FDB -6
    FDB -12
    FDB -19
    FDB -25
    FDB -31
    FDB -37
    FDB -43
    FDB -49
    FDB -54
    FDB -60
    FDB -65
    FDB -71
    FDB -76
    FDB -81
    FDB -85
    FDB -90
    FDB -94
    FDB -98
    FDB -102
    FDB -106
    FDB -109
    FDB -112
    FDB -115
    FDB -117
    FDB -120
    FDB -122
    FDB -123
    FDB -125
    FDB -126
    FDB -126
    FDB -127
    FDB -127
    FDB -127
    FDB -126
    FDB -126
    FDB -125
    FDB -123
    FDB -122
    FDB -120
    FDB -117
    FDB -115
    FDB -112
    FDB -109
    FDB -106
    FDB -102
    FDB -98
    FDB -94
    FDB -90
    FDB -85
    FDB -81
    FDB -76
    FDB -71
    FDB -65
    FDB -60
    FDB -54
    FDB -49
    FDB -43
    FDB -37
    FDB -31
    FDB -25
    FDB -19
    FDB -12
    FDB -6
COS_TABLE:
    FDB 127
    FDB 127
    FDB 126
    FDB 126
    FDB 125
    FDB 123
    FDB 122
    FDB 120
    FDB 117
    FDB 115
    FDB 112
    FDB 109
    FDB 106
    FDB 102
    FDB 98
    FDB 94
    FDB 90
    FDB 85
    FDB 81
    FDB 76
    FDB 71
    FDB 65
    FDB 60
    FDB 54
    FDB 49
    FDB 43
    FDB 37
    FDB 31
    FDB 25
    FDB 19
    FDB 12
    FDB 6
    FDB 0
    FDB -6
    FDB -12
    FDB -19
    FDB -25
    FDB -31
    FDB -37
    FDB -43
    FDB -49
    FDB -54
    FDB -60
    FDB -65
    FDB -71
    FDB -76
    FDB -81
    FDB -85
    FDB -90
    FDB -94
    FDB -98
    FDB -102
    FDB -106
    FDB -109
    FDB -112
    FDB -115
    FDB -117
    FDB -120
    FDB -122
    FDB -123
    FDB -125
    FDB -126
    FDB -126
    FDB -127
    FDB -127
    FDB -127
    FDB -126
    FDB -126
    FDB -125
    FDB -123
    FDB -122
    FDB -120
    FDB -117
    FDB -115
    FDB -112
    FDB -109
    FDB -106
    FDB -102
    FDB -98
    FDB -94
    FDB -90
    FDB -85
    FDB -81
    FDB -76
    FDB -71
    FDB -65
    FDB -60
    FDB -54
    FDB -49
    FDB -43
    FDB -37
    FDB -31
    FDB -25
    FDB -19
    FDB -12
    FDB -6
    FDB 0
    FDB 6
    FDB 12
    FDB 19
    FDB 25
    FDB 31
    FDB 37
    FDB 43
    FDB 49
    FDB 54
    FDB 60
    FDB 65
    FDB 71
    FDB 76
    FDB 81
    FDB 85
    FDB 90
    FDB 94
    FDB 98
    FDB 102
    FDB 106
    FDB 109
    FDB 112
    FDB 115
    FDB 117
    FDB 120
    FDB 122
    FDB 123
    FDB 125
    FDB 126
    FDB 126
    FDB 127
TAN_TABLE:
    FDB 0
    FDB 1
    FDB 2
    FDB 3
    FDB 4
    FDB 5
    FDB 6
    FDB 7
    FDB 8
    FDB 9
    FDB 11
    FDB 12
    FDB 13
    FDB 15
    FDB 16
    FDB 18
    FDB 20
    FDB 22
    FDB 24
    FDB 27
    FDB 30
    FDB 33
    FDB 37
    FDB 42
    FDB 48
    FDB 56
    FDB 66
    FDB 80
    FDB 101
    FDB 120
    FDB 120
    FDB 120
    FDB -120
    FDB -120
    FDB -120
    FDB -120
    FDB -101
    FDB -80
    FDB -66
    FDB -56
    FDB -48
    FDB -42
    FDB -37
    FDB -33
    FDB -30
    FDB -27
    FDB -24
    FDB -22
    FDB -20
    FDB -18
    FDB -16
    FDB -15
    FDB -13
    FDB -12
    FDB -11
    FDB -9
    FDB -8
    FDB -7
    FDB -6
    FDB -5
    FDB -4
    FDB -3
    FDB -2
    FDB -1
    FDB 0
    FDB 1
    FDB 2
    FDB 3
    FDB 4
    FDB 5
    FDB 6
    FDB 7
    FDB 8
    FDB 9
    FDB 11
    FDB 12
    FDB 13
    FDB 15
    FDB 16
    FDB 18
    FDB 20
    FDB 22
    FDB 24
    FDB 27
    FDB 30
    FDB 33
    FDB 37
    FDB 42
    FDB 48
    FDB 56
    FDB 66
    FDB 80
    FDB 101
    FDB 120
    FDB 120
    FDB 120
    FDB -120
    FDB -120
    FDB -120
    FDB -120
    FDB -101
    FDB -80
    FDB -66
    FDB -56
    FDB -48
    FDB -42
    FDB -37
    FDB -33
    FDB -30
    FDB -27
    FDB -24
    FDB -22
    FDB -20
    FDB -18
    FDB -16
    FDB -15
    FDB -13
    FDB -12
    FDB -11
    FDB -9
    FDB -8
    FDB -7
    FDB -6
    FDB -5
    FDB -4
    FDB -3
    FDB -2
    FDB -1
