; --- Motorola 6809 backend (Vectrex) title='TRIANGLE' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "../include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1998"
    FCB $80
    FDB music1
    FCB $F8,$50,$20,-$45
    FCC "TRIANGLE"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
INIT_ONCE:
    LDA #$80
    STA VIA_t1_cnt_lo
main: JSR Wait_Recal
    JSR Intensity_5F ; set default intensity
    JSR Reset0Ref ; center beam
    JSR MAIN
    BRA main

INTENS EQU 95
TXT_X EQU 65486
TXT_Y EQU 40
MAIN: ; function
; --- function main ---
    LDD #65486
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #40
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_0
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$32
    LDB #$1E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$9C
    LDB #$CE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$64
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$64
    LDB #$CE
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$D4
    LDB #$AC
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$30
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$30
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$D0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D0
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$00
    LDB #$5A
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$1A
    LDB #$F1
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$E2
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$E6
    LDB #$F1
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$E6
    LDB #$0F
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$1E
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$1A
    LDB #$0F
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$B0
    LDB #$14
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FA
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F8
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F8
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FA
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$06
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$06
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$02
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$4A
    JSR Intensity_a
    LDA #$3C
    LDB #$19
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$00
    LDB #$46
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$09
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$09
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$09
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$F9
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$07
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$F7
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$F8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FA
    LDB #$F9
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F8
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F8
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F7
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F7
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F7
    LDB #$FF
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$00
    LDB #$B0
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$05
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$FC
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$F9
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$F9
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$FA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$FB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F8
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$F9
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$06
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FB
    LDB #$06
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$09
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$04
    LDB #$08
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$07
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$06
    LDB #$07
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$08
    LDB #$04
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$09
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$09
    LDB #$01
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    RTS

;***************************************************************************
; RUNTIME SECTION
;***************************************************************************
VECTREX_PRINT_TEXT:
    ; Wait_Recal set DP=$D0 and zeroed beam; just load U,Y,X and call BIOS
    LDU VAR_ARG2   ; string pointer (high-bit terminated)
    LDA VAR_ARG1+1 ; Y
    LDB VAR_ARG0+1 ; X
    JSR Print_Str_d
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
; String literals (classic FCC + $80 terminator)
STR_0:
    FCC "TRIANGLE"
    FCB $80
; Call argument scratch space
VAR_ARG0 EQU RESULT+26
VAR_ARG1 EQU RESULT+28
VAR_ARG2 EQU RESULT+30
VAR_ARG3 EQU RESULT+32
VAR_ARG4 EQU RESULT+34
