; --- Motorola 6809 backend (Vectrex) title='VECTREX STEP9' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8,$50,$20,-$45
    FCC "VECTREX STEP9"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

MAIN_LOOP:
    JSR Wait_Recal
    LDA #$D0
    TFR A,DP
    JSR Intensity_5F
    JSR Reset0Ref
    JSR MAIN
    BRA MAIN_LOOP

I_STRONG EQU 95
I_MED EQU 64
I_DIM EQU 40
MAIN: ; function
; --- function main ---
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$4B
    LDB #$AD
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$53
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$53
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$4B
    LDB #$53
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$F4
    LDB #$0C
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3F
    LDB #$5F
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$C1
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$C1
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$C1
    LDB #$5F
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$F4
    LDB #$F4
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$B5
    LDB #$53
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$AD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$AD
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$B5
    LDB #$AD
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$0C
    LDB #$F4
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$C1
    LDB #$A1
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$3F
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$3F
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3F
    LDB #$A1
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$0C
    LDB #$0C
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3C
    LDB #$BA
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$46
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$46
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3C
    LDB #$46
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$CE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$CE
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D8
    LDB #$46
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$BA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$BA
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D8
    LDB #$BA
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$32
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$32
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$40
    JSR Intensity_a
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$34
    LDB #$C2
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$3E
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$3E
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$34
    LDB #$3E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$D6
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D6
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$E0
    LDB #$3E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$C2
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$C2
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$E0
    LDB #$C2
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$2A
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$2A
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D8
    LDB #$BA
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$46
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$46
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D8
    LDB #$46
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$E4
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$BC
    LDB #$46
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$BA
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$BA
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$BC
    LDB #$BA
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$1C
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$CA
    LDB #$DC
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$CA
    LDB #$D3
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$CE
    LDB #$2E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$D0
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$BE
    LDB #$2E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$C0
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$28
    JSR Intensity_a
    LDA #$29
    LDB #$AB
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$4F
    LDB #$26
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$72
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$9A
    LDB #$05
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$E5
    LDB #$91
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$67
    LDB #$D0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$1A
    LDB #$5C
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$DD
    LDB #$54
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$9E
    LDB #$C5
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$27
    LDB #$94
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$5E
    LDB #$12
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$72
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$A9
    LDB #$1B
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D0
    LDB #$98
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$5D
    LDB #$BD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$2A
    LDB #$4E
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$ED
    LDB #$61
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$95
    LDB #$D8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$13
    LDB #$8F
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$6B
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$6F
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$B8
    LDB #$2F
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$BE
    LDB #$A2
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$4F
    LDB #$AE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$3B
    LDB #$3D
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FC
    LDB #$6B
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$8F
    LDB #$EB
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$8E
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$6F
    LDB #$E8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$07
    LDB #$69
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$C8
    LDB #$41
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$AF
    LDB #$B0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$3E
    LDB #$A0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$4B
    LDB #$2B
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$70
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$97
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$EA
    LDB #$90
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$69
    LDB #$D4
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$16
    LDB #$5F
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D9
    LDB #$51
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$A1
    LDB #$C0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$2C
    LDB #$96
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$5A
    LDB #$17
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$73
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$A5
    LDB #$15
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D5
    LDB #$96
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$60
    LDB #$C2
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$26
    LDB #$51
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$E9
    LDB #$5F
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$28
    JSR Intensity_a
    LDA #$0A
    LDB #$04
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    RTS

    INCLUDE "runtime/vectorlist_runtime.asm"
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
; Call argument scratch space
VAR_ARG0 EQU RESULT+26
VAR_ARG1 EQU RESULT+28
VAR_ARG2 EQU RESULT+30
VAR_ARG3 EQU RESULT+32
VAR_ARG4 EQU RESULT+34
