; --- Motorola 6809 backend (Vectrex) title='VECTREX' origin=$0000 ---
        ORG $0000
;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "../include/VECTREX.I"

;***************************************************************************
; HEADER SECTION
;***************************************************************************
    FCC "g GCE 1982"
    FCB $80
    FDB music1
    FCB $F8,$50,$20,-$45
    FCC "VECTREX"
    FCB $80
    FCB 0

;***************************************************************************
; CODE SECTION
;***************************************************************************
    JMP START

START:
    LDA #$80
    STA VIA_t1_cnt_lo
    LDX #Vec_Default_Stk
    TFR X,S

MAIN_LOOP:
    JSR Wait_Recal
    LDA #$D0
    TFR A,DP
    JSR Intensity_5F
    JSR Reset0Ref
    JSR MAIN
    BRA MAIN_LOOP

I_STRONG EQU 95
I_MED EQU 64
I_DIM EQU 40
MAIN: ; function
; --- function main ---
    LDD VAR_STAGE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #1
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    ADDD TMPRIGHT
    STD RESULT
    LDX RESULT
    LDU #VAR_STAGE
    STU TMPPTR
    STX ,U
    LDD VAR_STAGE
    STD RESULT
    LDD RESULT
    STD TMPLEFT
    LDD #400
    STD RESULT
    LDD RESULT
    STD TMPRIGHT
    LDD TMPLEFT
    SUBD TMPRIGHT
    LDD #0
    STD RESULT
    BGT CT_2
    BRA CE_3
CT_2:
    LDD #1
    STD RESULT
CE_3:
    LDD RESULT
    LBEQ IF_NEXT_1
    LDD #400
    STD RESULT
    LDX RESULT
    LDU #VAR_STAGE
    STU TMPPTR
    STX ,U
    LBRA IF_END_0
IF_NEXT_1:
IF_END_0:
    LDD #65476
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #96
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #STR_0
    STX RESULT
    LDD RESULT
    STD VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    CLRA
    CLRB
    STD RESULT
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$5A
    LDB #$B2
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$4E
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$4E
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$5A
    LDB #$4E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$EC
    LDB #$16
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$46
    LDB #$64
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$BA
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$BA
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$BA
    LDB #$64
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$EC
    LDB #$EA
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$A6
    LDB #$4E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B2
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B2
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$A6
    LDB #$B2
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$14
    LDB #$EA
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$BA
    LDB #$9C
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$46
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$46
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$46
    LDB #$9C
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$14
    LDB #$16
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$44
    LDB #$B8
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$48
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$48
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$44
    LDB #$48
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$C9
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$C9
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D6
    LDB #$48
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B8
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D6
    LDB #$B8
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$37
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$37
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$40
    JSR Intensity_a
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3A
    LDB #$C0
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$40
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$40
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$3A
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$D2
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$D2
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$DE
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$C0
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$C0
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$DE
    LDB #$C0
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$2E
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$2E
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    JSR Intensity_5F
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D6
    LDB #$B8
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$48
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$48
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$D6
    LDB #$48
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$DC
    LDB #$00
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$B2
    LDB #$48
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B8
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$B8
    JSR Draw_Line_d
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$B2
    LDB #$B8
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$24
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$C0
    LDB #$DC
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FD
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FD
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$03
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$03
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    JSR Intensity_5F
    LDA #$C0
    LDB #$D3
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FF
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FF
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$01
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$01
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$C6
    LDB #$2E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$C8
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$B6
    LDB #$2E
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    LDA #$D0
    TFR A,DP
    JSR Reset0Ref
    LDA #$40
    JSR Intensity_a
    LDA #$B8
    LDB #$40
    JSR Moveto_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$FE
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$00
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$FE
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$00
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$02
    JSR Draw_Line_d
    CLR Vec_Misc_Count
    LDA #$02
    LDB #$00
    JSR Draw_Line_d
    CLRA
    CLRB
    STD RESULT
    RTS

    INCLUDE "../runtime/vectorlist_runtime.asm"
VECTREX_PRINT_TEXT:
    ; Wait_Recal set DP=$D0 and zeroed beam; just load U,Y,X and call BIOS
    LDU VAR_ARG2   ; string pointer (high-bit terminated)
    LDA VAR_ARG1+1 ; Y
    LDB VAR_ARG0+1 ; X
    JSR Print_Str_d
    RTS
;***************************************************************************
; DATA SECTION
;***************************************************************************
; Variables (in RAM)
RESULT    EQU $C880
TMPLEFT   EQU RESULT+2
TMPRIGHT  EQU RESULT+4
TMPPTR    EQU RESULT+6
VAR_STAGE EQU RESULT+26
; String literals (classic FCC + $80 terminator)
STR_0:
    FCC "VECTREX"
    FCB $80
; Call argument scratch space
VAR_ARG0 EQU RESULT+28
VAR_ARG1 EQU RESULT+30
VAR_ARG2 EQU RESULT+32
VAR_ARG3 EQU RESULT+34
VAR_ARG4 EQU RESULT+36
