
; === RAM VARIABLE DEFINITIONS ===
;***************************************************************************
RESULT               EQU $C880+$00   ; Main result temporary (2 bytes)
TMPPTR               EQU $C880+$02   ; Temporary pointer (2 bytes)
TMPPTR2              EQU $C880+$04   ; Temporary pointer 2 (2 bytes)
TEMP_YX              EQU $C880+$06   ; Temporary Y/X coordinate storage (2 bytes)
DRAW_VEC_X           EQU $C880+$08   ; Vector draw X offset (1 bytes)
DRAW_VEC_Y           EQU $C880+$09   ; Vector draw Y offset (1 bytes)
DRAW_VEC_INTENSITY   EQU $C880+$0A   ; Vector intensity override (0=use vector data) (1 bytes)
MIRROR_PAD           EQU $C880+$0B   ; Safety padding to prevent MIRROR flag corruption (16 bytes)
MIRROR_X             EQU $C880+$1B   ; X mirror flag (0=normal, 1=flip) (1 bytes)
MIRROR_Y             EQU $C880+$1C   ; Y mirror flag (0=normal, 1=flip) (1 bytes)
DRAW_LINE_ARGS       EQU $C880+$1D   ; DRAW_LINE argument buffer (x0,y0,x1,y1,intensity) (10 bytes)
VLINE_DX_16          EQU $C880+$27   ; DRAW_LINE dx (16-bit) (2 bytes)
VLINE_DY_16          EQU $C880+$29   ; DRAW_LINE dy (16-bit) (2 bytes)
VLINE_DX             EQU $C880+$2B   ; DRAW_LINE dx clamped (8-bit) (1 bytes)
VLINE_DY             EQU $C880+$2C   ; DRAW_LINE dy clamped (8-bit) (1 bytes)
VLINE_DY_REMAINING   EQU $C880+$2D   ; DRAW_LINE remaining dy for segment 2 (16-bit) (2 bytes)
VLINE_DX_REMAINING   EQU $C880+$2F   ; DRAW_LINE remaining dx for segment 2 (16-bit) (2 bytes)
LEVEL_PTR            EQU $C880+$31   ; Pointer to currently loaded level data (2 bytes)
LEVEL_WIDTH          EQU $C880+$33   ; Level width (1 bytes)
LEVEL_HEIGHT         EQU $C880+$34   ; Level height (1 bytes)
LEVEL_TILE_SIZE      EQU $C880+$35   ; Tile size (1 bytes)
PSG_MUSIC_PTR        EQU $C880+$36   ; PSG music data pointer (2 bytes)
PSG_MUSIC_START      EQU $C880+$38   ; PSG music start pointer (for loops) (2 bytes)
PSG_MUSIC_ACTIVE     EQU $C880+$3A   ; PSG music active flag (1 bytes)
PSG_IS_PLAYING       EQU $C880+$3B   ; PSG playing flag (1 bytes)
PSG_DELAY_FRAMES     EQU $C880+$3C   ; PSG frame delay counter (1 bytes)
SFX_PTR              EQU $C880+$3D   ; SFX data pointer (2 bytes)
SFX_ACTIVE           EQU $C880+$3F   ; SFX active flag (1 bytes)
VAR_ENEMY_ACTIVE     EQU $C880+$40   ; User variable: enemy_active (2 bytes)
VAR_MIN_BOUNCE_VY    EQU $C880+$42   ; User variable: MIN_BOUNCE_VY (2 bytes)
VAR_LOCATION_X_COORDS EQU $C880+$44   ; User variable: location_x_coords (2 bytes)
VAR_HOOK_GUN_X       EQU $C880+$46   ; User variable: hook_gun_x (2 bytes)
VAR_MOVE_SPEED       EQU $C880+$48   ; User variable: move_speed (2 bytes)
VAR_JOY_Y            EQU $C880+$4A   ; User variable: joy_y (2 bytes)
VAR_LOC_Y            EQU $C880+$4C   ; User variable: loc_y (2 bytes)
VAR_MAX_ENEMIES      EQU $C880+$4E   ; User variable: MAX_ENEMIES (2 bytes)
VAR_HOOK_INIT_Y      EQU $C880+$50   ; User variable: hook_init_y (2 bytes)
VAR_HOOK_ACTIVE      EQU $C880+$52   ; User variable: hook_active (2 bytes)
VAR_PLAYER_X         EQU $C880+$54   ; User variable: player_x (2 bytes)
VAR_JOYSTICK1_STATE  EQU $C880+$56   ; User variable: joystick1_state (2 bytes)
VAR_COUNTDOWN_ACTIVE EQU $C880+$58   ; User variable: countdown_active (2 bytes)
VAR_NUM_LOCATIONS    EQU $C880+$5A   ; User variable: num_locations (2 bytes)
VAR_SCREEN           EQU $C880+$5C   ; User variable: screen (2 bytes)
VAR_GROUND_Y         EQU $C880+$5E   ; User variable: GROUND_Y (2 bytes)
VAR_END_X            EQU $C880+$60   ; User variable: end_x (2 bytes)
VAR_END_Y            EQU $C880+$62   ; User variable: end_y (2 bytes)
VAR_ENEMY_SIZE       EQU $C880+$64   ; User variable: enemy_size (2 bytes)
VAR_PLAYER_FACING    EQU $C880+$66   ; User variable: player_facing (2 bytes)
VAR_STATE_MAP        EQU $C880+$68   ; User variable: STATE_MAP (2 bytes)
VAR_LOCATION_Y_COORDS EQU $C880+$6A   ; User variable: location_y_coords (2 bytes)
VAR_PLAYER_ANIM_SPEED EQU $C880+$6C   ; User variable: player_anim_speed (2 bytes)
VAR_TITLE_STATE      EQU $C880+$6E   ; User variable: title_state (2 bytes)
VAR_PLAYER_ANIM_FRAME EQU $C880+$70   ; User variable: player_anim_frame (2 bytes)
VAR_STATE_TITLE      EQU $C880+$72   ; User variable: STATE_TITLE (2 bytes)
VAR_START_Y          EQU $C880+$74   ; User variable: start_y (2 bytes)
VAR_PREV_JOY_Y       EQU $C880+$76   ; User variable: prev_joy_y (2 bytes)
VAR_LOCATION_GLOW_DIRECTION EQU $C880+$78   ; User variable: location_glow_direction (2 bytes)
VAR_HOOK_MAX_Y       EQU $C880+$7A   ; User variable: hook_max_y (2 bytes)
VAR_TITLE_INTENSITY  EQU $C880+$7C   ; User variable: title_intensity (2 bytes)
VAR_LEVEL_ENEMY_SPEED EQU $C880+$7E   ; User variable: level_enemy_speed (2 bytes)
VAR_LOCATION_NAMES   EQU $C880+$80   ; User variable: location_names (2 bytes)
VAR_LOC_X            EQU $C880+$82   ; User variable: loc_x (2 bytes)
VAR_CURRENT_LOCATION EQU $C880+$84   ; User variable: current_location (2 bytes)
VAR_JOY_X            EQU $C880+$86   ; User variable: joy_x (2 bytes)
VAR_CURRENT_MUSIC    EQU $C880+$88   ; User variable: current_music (2 bytes)
VAR_PLAYER_Y         EQU $C880+$8A   ; User variable: player_y (2 bytes)
VAR_ACTIVE_COUNT     EQU $C880+$8C   ; User variable: active_count (2 bytes)
VAR_HOOK_X           EQU $C880+$8E   ; User variable: hook_x (2 bytes)
VAR_PREV_JOY_X       EQU $C880+$90   ; User variable: prev_joy_x (2 bytes)
VAR_JOYSTICK_POLL_COUNTER EQU $C880+$92   ; User variable: joystick_poll_counter (2 bytes)
VAR_HOOK_Y           EQU $C880+$94   ; User variable: hook_y (2 bytes)
VAR_ENEMY_X          EQU $C880+$96   ; User variable: enemy_x (2 bytes)
VAR_PLAYER_ANIM_COUNTER EQU $C880+$98   ; User variable: player_anim_counter (2 bytes)
VAR_ENEMY_VY         EQU $C880+$9A   ; User variable: enemy_vy (2 bytes)
VAR_BOUNCE_DAMPING   EQU $C880+$9C   ; User variable: BOUNCE_DAMPING (2 bytes)
VAR_LOCATION_GLOW_INTENSITY EQU $C880+$9E   ; User variable: location_glow_intensity (2 bytes)
VAR_ENEMY_VX         EQU $C880+$A0   ; User variable: enemy_vx (2 bytes)
VAR_I                EQU $C880+$A2   ; User variable: i (2 bytes)
VAR_START_X          EQU $C880+$A4   ; User variable: start_x (2 bytes)
VAR_COUNTDOWN_TIMER  EQU $C880+$A6   ; User variable: countdown_timer (2 bytes)
VAR_ENEMY_Y          EQU $C880+$A8   ; User variable: enemy_y (2 bytes)
VAR_LEVEL_ENEMY_COUNT EQU $C880+$AA   ; User variable: level_enemy_count (2 bytes)
VAR_STATE_GAME       EQU $C880+$AC   ; User variable: STATE_GAME (2 bytes)
VAR_GRAVITY          EQU $C880+$AE   ; User variable: GRAVITY (2 bytes)
VAR_ANIM_THRESHOLD   EQU $C880+$B0   ; User variable: anim_threshold (2 bytes)
VAR_COUNT            EQU $C880+$B2   ; User variable: count (2 bytes)
VAR_ABS_JOY          EQU $C880+$B4   ; User variable: abs_joy (2 bytes)
VAR_HOOK_GUN_Y       EQU $C880+$B6   ; User variable: hook_gun_y (2 bytes)
VAR_SPEED            EQU $C880+$B8   ; User variable: speed (2 bytes)
VAR_MIRROR_MODE      EQU $C880+$BA   ; User variable: mirror_mode (2 bytes)
VAR_JOYSTICK1_STATE_DATA EQU $C880+$BC   ; Mutable array 'joystick1_state' data (6 elements x 2 bytes) (12 bytes)
VAR_ENEMY_ACTIVE_DATA EQU $C880+$C8   ; Mutable array 'enemy_active' data (8 elements x 2 bytes) (16 bytes)
VAR_ENEMY_X_DATA     EQU $C880+$D8   ; Mutable array 'enemy_x' data (8 elements x 2 bytes) (16 bytes)
VAR_ENEMY_Y_DATA     EQU $C880+$E8   ; Mutable array 'enemy_y' data (8 elements x 2 bytes) (16 bytes)
VAR_ENEMY_VX_DATA    EQU $C880+$F8   ; Mutable array 'enemy_vx' data (8 elements x 2 bytes) (16 bytes)
VAR_ENEMY_VY_DATA    EQU $C880+$108   ; Mutable array 'enemy_vy' data (8 elements x 2 bytes) (16 bytes)
VAR_ENEMY_SIZE_DATA  EQU $C880+$118   ; Mutable array 'enemy_size' data (8 elements x 2 bytes) (16 bytes)
VAR_ARG0             EQU $CFE0   ; Function argument 0 (16-bit) (2 bytes)
VAR_ARG1             EQU $CFE2   ; Function argument 1 (16-bit) (2 bytes)
VAR_ARG2             EQU $CFE4   ; Function argument 2 (16-bit) (2 bytes)
VAR_ARG3             EQU $CFE6   ; Function argument 3 (16-bit) (2 bytes)
VAR_ARG4             EQU $CFE8   ; Function argument 4 (16-bit) (2 bytes)
CURRENT_ROM_BANK     EQU $CFEA   ; Current ROM bank ID (multibank tracking) (1 bytes)


; ================================================
    ORG $0000  ; Sequential bank model
    ; Reserved for future code overflow


; ================================================
