; VPy M6809 Assembly (Vectrex)
; ROM: 524288 bytes
; Multibank cartridge: 32 banks (16KB each)
; Helpers bank: 31 (fixed bank at $4000-$7FFF)

; ================================================


; === RAM VARIABLE DEFINITIONS ===
;***************************************************************************
RESULT               EQU $C880+$00   ; Main result temporary (2 bytes)
TMPPTR               EQU $C880+$02   ; Temporary pointer (2 bytes)
TMPPTR2              EQU $C880+$04   ; Temporary pointer 2 (2 bytes)
VLINE_DX_16          EQU $C880+$06   ; DRAW_LINE dx (16-bit) (2 bytes)
VLINE_DY_16          EQU $C880+$08   ; DRAW_LINE dy (16-bit) (2 bytes)
VLINE_DX             EQU $C880+$0A   ; DRAW_LINE dx clamped (8-bit) (1 bytes)
VLINE_DY             EQU $C880+$0B   ; DRAW_LINE dy clamped (8-bit) (1 bytes)
VLINE_DY_REMAINING   EQU $C880+$0C   ; DRAW_LINE remaining dy for segment 2 (1 bytes)
VAR_ARG0             EQU $CFE0   ; Function argument 0 (16-bit) (2 bytes)
VAR_ARG1             EQU $CFE2   ; Function argument 1 (16-bit) (2 bytes)
VAR_ARG2             EQU $CFE4   ; Function argument 2 (16-bit) (2 bytes)
VAR_ARG3             EQU $CFE6   ; Function argument 3 (16-bit) (2 bytes)
VAR_ARG4             EQU $CFE8   ; Function argument 4 (16-bit) (2 bytes)


; ================================================

; VPy M6809 Assembly (Vectrex)
; ROM: 524288 bytes
; Multibank cartridge: 32 banks (16KB each)
; Helpers bank: 31 (fixed bank at $4000-$7FFF)

; ================================================

    ORG $0000

;***************************************************************************
; DEFINE SECTION
;***************************************************************************
    INCLUDE "VECTREX.I"
; External symbols (helpers and shared data)
Vec_Freq_Table EQU $C84D
VEC_EXPL_CHANS EQU $C854
DRAW_PAT_VL EQU $F437
Strip_Zeros EQU $F8B7
Vec_Rise_Index EQU $C839
RANDOM EQU $F517
RISE_RUN_ANGLE EQU $F593
Add_Score_a EQU $F85E
Mov_Draw_VL_ab EQU $F3B7
music9 EQU $FF26
MUSIC5 EQU $FE38
VEC_PATTERN EQU $C829
Delay_0 EQU $F579
VEC_RFRSH EQU $C83D
Vec_Default_Stk EQU $CBEA
RISE_RUN_X EQU $F5FF
Recalibrate EQU $F2E6
Vec_Twang_Table EQU $C851
MUSIC9 EQU $FF26
VEC_NUM_GAME EQU $C87A
Draw_VLc EQU $F3CE
musica EQU $FF44
Print_Str EQU $F495
GET_RUN_IDX EQU $F5DB
INIT_MUSIC EQU $F68D
Vec_Button_2_2 EQU $C817
INIT_VIA EQU $F14C
VEC_JOY_MUX_1_X EQU $C81F
VEC_RFRSH_LO EQU $C83D
VEC_TEXT_HEIGHT EQU $C82A
Draw_VL_a EQU $F3DA
Print_List_hw EQU $F385
music7 EQU $FEC6
Vec_SWI2_Vector EQU $CBF2
Print_Ships EQU $F393
VEC_JOY_MUX EQU $C81F
Rise_Run_Len EQU $F603
Draw_Pat_VL_a EQU $F434
MOV_DRAW_VL_D EQU $F3BE
DELAY_B EQU $F57A
VEC_COUNTERS EQU $C82E
music5 EQU $FE38
ADD_SCORE_A EQU $F85E
OBJ_WILL_HIT_U EQU $F8E5
Rot_VL_dft EQU $F637
MOVETO_IX_7F EQU $F30C
CLEAR_X_256 EQU $F545
VEC_0REF_ENABLE EQU $C824
PRINT_TEXT_STR_82781042 EQU $4019
VEC_PREV_BTNS EQU $C810
Vec_Counters EQU $C82E
VEC_EXPL_CHANB EQU $C85D
VEC_SEED_PTR EQU $C87B
Warm_Start EQU $F06C
OBJ_WILL_HIT EQU $F8F3
SET_REFRESH EQU $F1A2
Vec_Brightness EQU $C827
PRINT_SHIPS EQU $F393
VEC_BUTTON_2_4 EQU $C819
VEC_JOY_MUX_2_Y EQU $C822
Vec_Angle EQU $C836
Intensity_1F EQU $F29D
SOUND_BYTES EQU $F27D
VEC_BUTTON_1_4 EQU $C815
SOUND_BYTE_X EQU $F259
Vec_Button_2_3 EQU $C818
Vec_RiseRun_Len EQU $C83B
Clear_x_d EQU $F548
VEC_MAX_PLAYERS EQU $C84F
Dot_d EQU $F2C3
ROT_VL_MODE EQU $F62B
Vec_Expl_2 EQU $C859
Mov_Draw_VL_b EQU $F3B1
Sound_Bytes_x EQU $F284
RISE_RUN_LEN EQU $F603
VEC_FIRQ_VECTOR EQU $CBF5
Vec_Music_Ptr EQU $C853
Init_Music_x EQU $F692
DRAW_VL_B EQU $F3D2
VEC_JOY_RESLTN EQU $C81A
DRAW_LINE_D EQU $F3DF
Vec_Music_Work EQU $C83F
Reset0Int EQU $F36B
Clear_Score EQU $F84F
VEC_JOY_2_X EQU $C81D
VEC_BUTTON_1_2 EQU $C813
INTENSITY_1F EQU $F29D
Vec_Buttons EQU $C811
Print_List EQU $F38A
New_High_Score EQU $F8D8
Get_Run_Idx EQU $F5DB
MOV_DRAW_VLCS EQU $F3B5
VEC_BUTTON_1_1 EQU $C812
Init_Music_Buf EQU $F533
Draw_VL_mode EQU $F46E
Draw_VL_b EQU $F3D2
Vec_Pattern EQU $C829
Cold_Start EQU $F000
Draw_VLp_scale EQU $F40C
CLEAR_X_D EQU $F548
Vec_ADSR_Table EQU $C84F
Check0Ref EQU $F34F
Vec_Cold_Flag EQU $CBFE
Vec_Run_Index EQU $C837
VEC_EXPL_CHANA EQU $C853
Random_3 EQU $F511
DRAW_VL_A EQU $F3DA
Obj_Hit EQU $F8FF
Intensity_a EQU $F2AB
Vec_SWI3_Vector EQU $CBF2
Intensity_5F EQU $F2A5
Vec_Max_Games EQU $C850
DELAY_0 EQU $F579
Vec_Music_Chan EQU $C855
Sound_Byte_raw EQU $F25B
Init_OS EQU $F18B
MOV_DRAW_VLC_A EQU $F3AD
Wait_Recal EQU $F192
ROT_VL_DFT EQU $F637
VEC_BUTTON_1_3 EQU $C814
VEC_MUSIC_FREQ EQU $C861
Rise_Run_Angle EQU $F593
MOVETO_IX_FF EQU $F308
Vec_Max_Players EQU $C84F
READ_BTNS_MASK EQU $F1B4
CLEAR_X_B_A EQU $F552
RESET0REF EQU $F354
ADD_SCORE_D EQU $F87C
VEC_NMI_VECTOR EQU $CBFB
Vec_Music_Flag EQU $C856
Draw_VLp_7F EQU $F408
STRIP_ZEROS EQU $F8B7
VEC_MAX_GAMES EQU $C850
Draw_VL EQU $F3DD
Vec_Button_2_4 EQU $C819
musicb EQU $FF62
Move_Mem_a EQU $F683
Obj_Will_Hit EQU $F8F3
VEC_EXPL_1 EQU $C858
Vec_Dot_Dwell EQU $C828
DRAW_PAT_VL_D EQU $F439
Move_Mem_a_1 EQU $F67F
Vec_Prev_Btns EQU $C810
Delay_3 EQU $F56D
Vec_Button_1_4 EQU $C815
Vec_Expl_Chans EQU $C854
Vec_Joy_2_X EQU $C81D
INIT_OS EQU $F18B
Intensity_3F EQU $F2A1
PRINT_LIST EQU $F38A
musicd EQU $FF8F
Vec_Music_Twang EQU $C858
DRAW_VLP EQU $F410
Vec_Seed_Ptr EQU $C87B
VEC_BTN_STATE EQU $C80F
VEC_COUNTER_2 EQU $C82F
DEC_3_COUNTERS EQU $F55A
EXPLOSION_SND EQU $F92E
Intensity_7F EQU $F2A9
PRINT_LIST_HW EQU $F385
Rot_VL EQU $F616
INTENSITY_A EQU $F2AB
ROT_VL EQU $F616
DO_SOUND EQU $F289
Draw_VLp_FF EQU $F404
MUSICA EQU $FF44
DO_SOUND_X EQU $F28C
DOT_IX EQU $F2C1
DEC_6_COUNTERS EQU $F55E
MOV_DRAW_VL_AB EQU $F3B7
Get_Rise_Run EQU $F5EF
VEC_MUSIC_WK_A EQU $C842
Joy_Digital EQU $F1F8
DOT_HERE EQU $F2C5
DRAW_VLC EQU $F3CE
Vec_Loop_Count EQU $C825
Rise_Run_X EQU $F5FF
Delay_1 EQU $F575
MOVE_MEM_A_1 EQU $F67F
Vec_Num_Players EQU $C879
RANDOM_3 EQU $F511
Clear_Sound EQU $F272
Dec_Counters EQU $F563
MUSICD EQU $FF8F
VEC_MUSIC_PTR EQU $C853
music8 EQU $FEF8
Print_Str_hwyx EQU $F373
VEC_MUSIC_WK_5 EQU $C847
Xform_Run EQU $F65D
Vec_Music_Wk_5 EQU $C847
DOT_IX_B EQU $F2BE
Moveto_d_7F EQU $F2FC
Vec_0Ref_Enable EQU $C824
SOUND_BYTE_RAW EQU $F25B
ROT_VL_MODE_A EQU $F61F
DP_TO_C8 EQU $F1AF
Vec_Joy_1_Y EQU $C81C
Draw_Pat_VL_d EQU $F439
Vec_Counter_6 EQU $C833
Vec_Expl_Flag EQU $C867
VEC_JOY_2_Y EQU $C81E
Moveto_d EQU $F312
DRAW_VLP_7F EQU $F408
Xform_Rise EQU $F663
Vec_Num_Game EQU $C87A
GET_RISE_IDX EQU $F5D9
music6 EQU $FE76
Vec_Rfrsh_hi EQU $C83E
VEC_JOY_MUX_2_X EQU $C821
Delay_2 EQU $F571
Mov_Draw_VL_d EQU $F3BE
MUSIC1 EQU $FD0D
INTENSITY_7F EQU $F2A9
Vec_Duration EQU $C857
VECTREX_PRINT_TEXT EQU $4000
VEC_IRQ_VECTOR EQU $CBF8
PRINT_STR_D EQU $F37A
VEC_JOY_MUX_1_Y EQU $C820
Vec_Music_Wk_A EQU $C842
INIT_MUSIC_CHK EQU $F687
DRAW_VLP_FF EQU $F404
DRAW_VL_MODE EQU $F46E
CLEAR_SOUND EQU $F272
RISE_RUN_Y EQU $F601
Vec_Joy_Mux_2_X EQU $C821
music2 EQU $FD1D
MUSIC3 EQU $FD81
Reset0Ref_D0 EQU $F34A
Draw_VL_ab EQU $F3D8
Abs_b EQU $F58B
VEC_MUSIC_WK_6 EQU $C846
Moveto_ix_7F EQU $F30C
Init_VIA EQU $F14C
VEC_MUSIC_WORK EQU $C83F
DP_TO_D0 EQU $F1AA
music4 EQU $FDD3
Abs_a_b EQU $F584
Moveto_ix_a EQU $F30E
Vec_Joy_Mux_1_X EQU $C81F
READ_BTNS EQU $F1BA
SOUND_BYTES_X EQU $F284
MOVETO_X_7F EQU $F2F2
Vec_Joy_2_Y EQU $C81E
VEC_DURATION EQU $C857
Vec_Expl_ChanB EQU $C85D
Moveto_ix_FF EQU $F308
VEC_FREQ_TABLE EQU $C84D
SELECT_GAME EQU $F7A9
Vec_Counter_3 EQU $C830
DELAY_RTS EQU $F57D
VEC_JOY_1_X EQU $C81B
GET_RISE_RUN EQU $F5EF
Bitmask_a EQU $F57E
Vec_Joy_Mux EQU $C81F
Moveto_x_7F EQU $F2F2
DELAY_2 EQU $F571
VEC_MUSIC_CHAN EQU $C855
Vec_Music_Wk_7 EQU $C845
Vec_Joy_Mux_2_Y EQU $C822
MUSIC6 EQU $FE76
Vec_Str_Ptr EQU $C82C
VEC_DOT_DWELL EQU $C828
Vec_Counter_4 EQU $C831
DELAY_1 EQU $F575
PRINT_STR EQU $F495
Vec_Button_2_1 EQU $C816
Dec_6_Counters EQU $F55E
VEC_ADSR_TIMERS EQU $C85E
Vec_Expl_ChanA EQU $C853
VEC_BUTTON_2_3 EQU $C818
MOV_DRAW_VL_B EQU $F3B1
DRAW_VL EQU $F3DD
Rise_Run_Y EQU $F601
VEC_COUNTER_4 EQU $C831
WARM_START EQU $F06C
DELAY_3 EQU $F56D
Vec_Music_Wk_1 EQU $C84B
Vec_Expl_1 EQU $C858
DRAW_GRID_VL EQU $FF9F
Delay_b EQU $F57A
VEC_EXPL_FLAG EQU $C867
VEC_EXPL_CHAN EQU $C85C
Vec_High_Score EQU $CBEB
VEC_NUM_PLAYERS EQU $C879
BITMASK_A EQU $F57E
Vec_Text_Height EQU $C82A
Explosion_Snd EQU $F92E
VEC_EXPL_2 EQU $C859
Vec_Button_1_3 EQU $C814
INIT_MUSIC_BUF EQU $F533
Print_Str_yx EQU $F378
Vec_IRQ_Vector EQU $CBF8
VEC_MUSIC_WK_7 EQU $C845
MOV_DRAW_VL EQU $F3BC
DRAW_VLP_B EQU $F40E
VEC_ADSR_TABLE EQU $C84F
VEC_RFRSH_HI EQU $C83E
VEC_MUSIC_WK_1 EQU $C84B
DRAW_PAT_VL_A EQU $F434
Add_Score_d EQU $F87C
VEC_RUN_INDEX EQU $C837
Do_Sound_x EQU $F28C
Draw_VLcs EQU $F3D6
MOV_DRAW_VL_A EQU $F3B9
Init_Music EQU $F68D
Rot_VL_ab EQU $F610
VEC_ANGLE EQU $C836
Print_Str_d EQU $F37A
Vec_Text_HW EQU $C82A
Vec_Random_Seed EQU $C87D
Vec_RiseRun_Tmp EQU $C834
Moveto_ix EQU $F310
Vec_Rfrsh EQU $C83D
CHECK0REF EQU $F34F
Dot_List EQU $F2D5
VEC_COUNTER_5 EQU $C832
VEC_RISERUN_LEN EQU $C83B
Obj_Will_Hit_u EQU $F8E5
PRINT_LIST_CHK EQU $F38C
VEC_EXPL_3 EQU $C85A
Select_Game EQU $F7A9
VEC_LOOP_COUNT EQU $C825
Vec_Joy_1_X EQU $C81B
Rot_VL_Mode EQU $F62B
Get_Rise_Idx EQU $F5D9
XFORM_RISE EQU $F663
VEC_JOY_1_Y EQU $C81C
Vec_FIRQ_Vector EQU $CBF5
Dec_3_Counters EQU $F55A
Mov_Draw_VL EQU $F3BC
MOVETO_IX EQU $F310
Vec_Misc_Count EQU $C823
Delay_RTS EQU $F57D
Vec_Snd_Shadow EQU $C800
DOT_D EQU $F2C3
VEC_TWANG_TABLE EQU $C851
Clear_x_b_a EQU $F552
Mov_Draw_VLc_a EQU $F3AD
INIT_OS_RAM EQU $F164
Vec_Music_Wk_6 EQU $C846
INTENSITY_5F EQU $F2A5
Xform_Rise_a EQU $F661
Mov_Draw_VL_a EQU $F3B9
Vec_Counter_2 EQU $C82F
COMPARE_SCORE EQU $F8C7
VEC_COLD_FLAG EQU $CBFE
VEC_BRIGHTNESS EQU $C827
CLEAR_X_B EQU $F53F
VEC_RANDOM_SEED EQU $C87D
Dot_ix_b EQU $F2BE
DP_to_D0 EQU $F1AA
Clear_x_b_80 EQU $F550
VEC_DEFAULT_STK EQU $CBEA
MUSIC7 EQU $FEC6
DOT_LIST EQU $F2D5
RECALIBRATE EQU $F2E6
Vec_SWI_Vector EQU $CBFB
Clear_x_b EQU $F53F
Dot_here EQU $F2C5
Clear_C8_RAM EQU $F542
Compare_Score EQU $F8C7
VEC_TEXT_HW EQU $C82A
Xform_Run_a EQU $F65B
Vec_ADSR_Timers EQU $C85E
RESET_PEN EQU $F35B
Draw_Pat_VL EQU $F437
XFORM_RUN_A EQU $F65B
Vec_Joy_Resltn EQU $C81A
musicc EQU $FF7A
MOVETO_D EQU $F312
PRINT_TEXT_STR_68624562 EQU $4013
DRAW_VL_AB EQU $F3D8
Dot_ix EQU $F2C1
Set_Refresh EQU $F1A2
Draw_Grid_VL EQU $FF9F
Vec_Expl_Chan EQU $C85C
ROT_VL_AB EQU $F610
JOY_DIGITAL EQU $F1F8
DRAW_VLCS EQU $F3D6
VEC_STR_PTR EQU $C82C
Read_Btns_Mask EQU $F1B4
PRINT_STR_YX EQU $F378
VEC_COUNTER_1 EQU $C82E
VEC_EXPL_TIMER EQU $C877
Reset_Pen EQU $F35B
VEC_MUSIC_FLAG EQU $C856
VEC_BUTTON_2_1 EQU $C816
Dot_List_Reset EQU $F2DE
VEC_MISC_COUNT EQU $C823
music1 EQU $FD0D
JOY_ANALOG EQU $F1F5
PRINT_SHIPS_X EQU $F391
Init_Music_chk EQU $F687
MOVETO_IX_A EQU $F30E
DEC_COUNTERS EQU $F563
Init_OS_RAM EQU $F164
VEC_SND_SHADOW EQU $C800
Draw_VLp_b EQU $F40E
INIT_MUSIC_X EQU $F692
Sound_Byte EQU $F256
Read_Btns EQU $F1BA
VEC_COUNTER_6 EQU $C833
Vec_Joy_Mux_1_Y EQU $C820
Vec_Button_1_2 EQU $C813
music3 EQU $FD81
CLEAR_SCORE EQU $F84F
VEC_BUTTONS EQU $C811
CLEAR_X_B_80 EQU $F550
Vec_Button_1_1 EQU $C812
VEC_COUNTER_3 EQU $C830
VEC_EXPL_4 EQU $C85B
MOVETO_D_7F EQU $F2FC
Draw_Line_d EQU $F3DF
VEC_RISERUN_TMP EQU $C834
Print_List_chk EQU $F38C
XFORM_RISE_A EQU $F661
DRAW_VLP_SCALE EQU $F40C
MUSIC8 EQU $FEF8
Joy_Analog EQU $F1F5
VEC_TEXT_WIDTH EQU $C82B
Vec_Counter_1 EQU $C82E
MOVE_MEM_A EQU $F683
Vec_Text_Width EQU $C82B
MUSICC EQU $FF7A
DP_to_C8 EQU $F1AF
Vec_Counter_5 EQU $C832
WAIT_RECAL EQU $F192
Vec_Expl_4 EQU $C85B
VEC_MUSIC_TWANG EQU $C858
Vec_Expl_Timer EQU $C877
DOT_LIST_RESET EQU $F2DE
Sound_Byte_x EQU $F259
INTENSITY_3F EQU $F2A1
Mov_Draw_VLcs EQU $F3B5
RESET0REF_D0 EQU $F34A
Vec_NMI_Vector EQU $CBFB
VEC_HIGH_SCORE EQU $CBEB
Vec_Rfrsh_lo EQU $C83D
CLEAR_C8_RAM EQU $F542
RESET0INT EQU $F36B
Vec_Btn_State EQU $C80F
Random EQU $F517
VEC_SWI2_VECTOR EQU $CBF2
MUSIC4 EQU $FDD3
PRINT_STR_HWYX EQU $F373
Draw_VLp EQU $F410
MUSICB EQU $FF62
VEC_SWI_VECTOR EQU $CBFB
Sound_Bytes EQU $F27D
VEC_SWI3_VECTOR EQU $CBF2
ABS_A_B EQU $F584
Rot_VL_Mode_a EQU $F61F
VEC_RISE_INDEX EQU $C839
Vec_Music_Freq EQU $C861
XFORM_RUN EQU $F65D
NEW_HIGH_SCORE EQU $F8D8
MUSIC2 EQU $FD1D
OBJ_HIT EQU $F8FF
Print_Ships_x EQU $F391
VEC_BUTTON_2_2 EQU $C817
ABS_B EQU $F58B
Reset0Ref EQU $F354
Clear_x_256 EQU $F545
Vec_Expl_3 EQU $C85A
COLD_START EQU $F000
Do_Sound EQU $F289
SOUND_BYTE EQU $F256


;***************************************************************************
; CARTRIDGE HEADER
;***************************************************************************
    FCC "g GCE 2025"
    FCB $80                 ; String terminator
    FDB music1              ; Music pointer
    FCB $F8,$50,$20,$BB     ; Height, Width, Rel Y, Rel X
    FCC "MULTIBANK PDB TEST"
    FCB $80                 ; String terminator
    FCB 0                   ; End of header

;***************************************************************************
; CODE SECTION
;***************************************************************************

START:
    LDA #$D0
    TFR A,DP        ; Set Direct Page for BIOS
    CLR $C80E        ; Initialize Vec_Prev_Btns
    LDA #$80
    STA VIA_t1_cnt_lo
    LDS #$CBFF       ; Initialize stack
; Bank 0 ($0000) is active; fixed bank 31 ($4000-$7FFF) always visible
    JMP MAIN

;***************************************************************************
; MAIN PROGRAM
;***************************************************************************

MAIN:
    ; Initialize global variables
    ; Call main() for initialization
    ; SET_INTENSITY: Set drawing intensity
    LDD #127
    STD RESULT
    LDA RESULT+1    ; Load intensity (8-bit)
    JSR Intensity_a
    LDD #0
    STD RESULT

.MAIN_LOOP:
    JSR LOOP_BODY
    LBRA .MAIN_LOOP

LOOP_BODY:
    JSR Wait_Recal   ; Synchronize with screen refresh (mandatory)
    JSR Reset0Ref    ; Reset beam to center (0,0)
    ; PRINT_TEXT: Print text at position
    LDD #-70
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #PRINT_TEXT_STR_68624562      ; Pointer to string in helpers bank
    STX VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    LDD #0
    STD RESULT
    ; PRINT_TEXT: Print text at position
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG0
    LDD #0
    STD RESULT
    LDD RESULT
    STD VAR_ARG1
    LDX #PRINT_TEXT_STR_82781042      ; Pointer to string in helpers bank
    STX VAR_ARG2
    JSR VECTREX_PRINT_TEXT
    LDD #0
    STD RESULT
    RTS


; ================================================
